### ISSUE TITLE
Client crash on beam attacks

### ISSUE THREAD

**Issue by doctorkreger** [Thutmose/Pokecube#109]
#### Issue Description:
Arek Lewis (keifer@umich.edu)
---- Minecraft Crash Report ----

WARNING: coremods are present:
 LoadingPlugin (RandomThings-MC1.10-3.7.4.jar)
 AppleCore (AppleCore-mc1.10.2-1.3.5.jar)
 NWRTweak (redstonepaste-mc1.9.4-1.7.4.jar)
 EnderCorePlugin (EnderCore-1.10.2-0.4.1.37-beta.jar)
Contact their authors BEFORE contacting forge

// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 7/11/16 12:21 PM
Description: Rendering entity in world

java.lang.NullPointerException: Rendering entity in world
at pokecube.core.moves.animations.ParticleBeam.clientAnimation(ParticleBeam.java:51)
at pokecube.core.client.render.RenderMoves.doRender(RenderMoves.java:32)
at pokecube.core.client.render.RenderMoves.func_76986_a(RenderMoves.java:13)
at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:384)
at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:368)
at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:801)
at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1727)
at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1556)
at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1335)
at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
at net.minecraft.client.main.Main.main(SourceFile:124)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
--------------------------------------------------------------------------------------

#### What happens:
When using a beam ability the client crashes

#### What you expected to happen:

Not that!

#### Steps to reproduce:
- Update to latest version
- Use beam
____
#### Affected Versions (Do *not* use "latest"):

- Pokecube Core:4.2.2
- Pokecube Revival (if applicable):4.1.14
- Pokecube Mobs (if applicable):2.2.1
- Minecraft: 1.10.2
- Forge:1.10.2-12.18.0.2010

**Comment by Thutmose** [comment]
Should be fixed for next release.

**Comment by Thutmose** [comment]
Should be fixed in 4.3.0, which has been uploaded.
