### ISSUE TITLE
Crash :( 

### ISSUE THREAD

**Issue by RebeccaRedstone** [Thutmose/Pokecube#131]
Getting a crash on both server and client. Will not launch the game. Only using pokecube mods and dependencies 
#### What happens:

Game/Server crashes.
#### What you expected to happen:

To load the game. :)
#### Steps to reproduce:
1. Launch game. 
2. Crash.
3. Be sad.
   ...

---
#### Affected Versions (Do _not_ use "latest"):
- Pokecube Core: 4.4.6
- Pokecube Revival (if applicable): 4.3.5
- Pokecube Mobs (if applicable): 2.2.2
- Minecraft: 1.10.2
- Forge: 1.10.2.18.1.2046 (also tried versions ending in 2011 and 2014)

Thank you for any help!

**Comment by Thutmose** [comment]
do you also have a version of ThutCore?  See if you can get a crash report?

**Comment by RebeccaRedstone** [comment]
I have a crash report - forgot to include it xD 

Using ThutsCore v 1.10.2 4.0.0

---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 05/08/16 3:27 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.NoSuchMethodError: net.minecraftforge.fml.common.registry.PersistentRegistryManager.createRegistry(Lnet/minecraft/util/ResourceLocation;Ljava/lang/Class;Lnet/minecraft/util/ResourceLocation;IIZLnet/minecraftforge/fml/common/registry/IForgeRegistry$AddCallback;Lnet/minecraftforge/fml/common/registry/IForgeRegistry$ClearCallback;Lnet/minecraftforge/fml/common/registry/IForgeRegistry$CreateCallback;Lnet/minecraftforge/fml/common/registry/IForgeRegistry$SubstitutionCallback;)Lnet/minecraftforge/fml/common/registry/FMLControlledNamespacedRegistry;
    at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:186)
    at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:562)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:216)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:439)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoSuchMethodError: net.minecraftforge.fml.common.registry.PersistentRegistryManager.createRegistry(Lnet/minecraft/util/ResourceLocation;Ljava/lang/Class;Lnet/minecraft/util/ResourceLocation;IIZLnet/minecraftforge/fml/common/registry/IForgeRegistry$AddCallback;Lnet/minecraftforge/fml/common/registry/IForgeRegistry$ClearCallback;Lnet/minecraftforge/fml/common/registry/IForgeRegistry$CreateCallback;Lnet/minecraftforge/fml/common/registry/IForgeRegistry$SubstitutionCallback;)Lnet/minecraftforge/fml/common/registry/FMLControlledNamespacedRegistry;
    at thut.api.terrain.BiomeDatabase.<clinit>(BiomeDatabase.java:22)
    at thut.core.common.ThutCore.<init>(ThutCore.java:45)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
    at java.lang.Class.newInstance(Class.java:438)
    at net.minecraftforge.fml.common.ILanguageAdapter$JavaAdapter.getNewInstance(ILanguageAdapter.java:193)
    at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:551)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:235)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:213)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:142)
    at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:531)
    ... 10 more

## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.10.2
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 3012018328 bytes (2872 MB) / 3186360320 bytes (3038 MB) up to 3186360320 bytes (3038 MB)
    JVM Flags: 7 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmx3072M -Xms3072M
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP 9.32 Powered by Forge 12.18.1.2011 13 mods loaded, 13 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UC  mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UC  FML{8.0.99.99} [Forge Mod Loader](forge-1.10.2-12.18.1.2011.jar) 
    UC  Forge{12.18.1.2011} [Minecraft Forge](forge-1.10.2-12.18.1.2011.jar) 
    UC  Baubles{1.2.1.0} [Baubles](Baubles-1.9.4-1.2.1.0 %281%29.jar) 
    UE  thutcore{4.0.0} [ThutCore](thutcore-1.10.2-4.0.0.jar) 
    UC  NBTEditpqb{1.10.2-2.0.0} [In-game NBTEdit - Pokecube Edition](Pokecube Core-4.4.6.jar) 
    UE  pokecube{4.4.6} [Pokécube Core](Pokecube Core-4.4.6.jar) 
    UC  pokecube_ml{0.1.0} [Pokecube Model Loader](Pokecube Core-4.4.6.jar) 
    UE  pokecube_mobs{2.2.2} [Pokécube Mobs](Pokecube Mobs-2.2.2.jar) 
    UE  pokecube_origin{@VERSION@} [Pokecube Origin](Pokecube Mobs-2.2.2.jar) 
    UE  pokecube_adventures{4.3.5} [Pokécube Revival](Pokecube Revival-4.3.5.jar) 
    UC  pokecube_compat{1.0} [Pokecube Compat](Pokecube Revival-4.3.5.jar) 
    UE  pokeplayer{@VERSION} [Pokecube Mystery Dungeon](Pokecube Revival-4.3.5.jar) 
    Loaded coremods (and transformers): 
    GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 20.19.15.4454' Renderer: 'Intel(R) HD Graphics 520'

**Comment by Thutmose** [comment]
Hmm, try using the previous version of thutcore?

I tested those mods with forge 2046 and it ran fine, I wonder if you need to re-install forge or something?

**Comment by Thutmose** [comment]
ohh, Your forge version is 2011, so that will require the previous version of ThutCore.

**Comment by Thutmose** [comment]
This shouldn't occur anymore, so closing the issue.
