### ISSUE TITLE
my minecraft crashed

### ISSUE THREAD

**Issue by boxboygs** [Thutmose/Pokecube#181]
so i was starting the game after a few seconds of loading the world with these mods it crashes pokecube mobs,pokecube core,thutcore,thut wearables and thut bling here is a crash report if you know what to do---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 3/30/17 6:49 AM
Description: Ticking entity

java.lang.NoSuchFieldError: x
	at pokecube.core.ai.utils.PokeNavigator.func_75501_e(PokeNavigator.java:272)
	at pokecube.core.entity.pokemobs.helper.EntityAiPokemob.func_70626_be(EntityAiPokemob.java:1282)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2255)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:573)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:171)
	at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:39)
	at pokecube.core.entity.pokemobs.helper.EntityTameablePokemob.func_70636_d(EntityTameablePokemob.java:515)
	at pokecube.core.entity.pokemobs.helper.EntityEvolvablePokemob.func_70636_d(EntityEvolvablePokemob.java:398)
	at pokecube.core.entity.pokemobs.helper.EntityAiPokemob.func_70636_d(EntityAiPokemob.java:812)
	at pokecube.core.entity.pokemobs.helper.EntityHungryPokemob.func_70636_d(EntityHungryPokemob.java:311)
	at pokecube.core.entity.pokemobs.helper.EntityPokemobBase.func_70636_d(EntityPokemobBase.java:596)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2085)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:296)
	at pokecube.core.entity.pokemobs.helper.EntityTameablePokemob.func_70071_h_(EntityTameablePokemob.java:550)
	at pokecube.core.entity.pokemobs.helper.EntityStatsPokemob.func_70071_h_(EntityStatsPokemob.java:555)
	at pokecube.core.entity.pokemobs.helper.EntityEvolvablePokemob.func_70071_h_(EntityEvolvablePokemob.java:404)
	at pokecube.core.entity.pokemobs.helper.EntityMountablePokemob.func_70071_h_(EntityMountablePokemob.java:175)
	at pokecube.core.entity.pokemobs.helper.EntityAiPokemob.func_70071_h_(EntityAiPokemob.java:838)
	at pokecube.core.entity.pokemobs.helper.EntityHungryPokemob.func_70071_h_(EntityHungryPokemob.java:317)
	at pokecube.core.entity.pokemobs.helper.EntityPokemobBase.func_70071_h_(EntityPokemobBase.java:644)
	at net.minecraft.world.World.func_72866_a(World.java:1987)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:840)
	at net.minecraft.world.World.func_72870_g(World.java:1957)
	at net.minecraft.world.World.func_72939_s(World.java:1773)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at pokecube.core.ai.utils.PokeNavigator.func_75501_e(PokeNavigator.java:272)
	at pokecube.core.entity.pokemobs.helper.EntityAiPokemob.func_70626_be(EntityAiPokemob.java:1282)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2255)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:573)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:171)
	at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:39)
	at pokecube.core.entity.pokemobs.helper.EntityTameablePokemob.func_70636_d(EntityTameablePokemob.java:515)
	at pokecube.core.entity.pokemobs.helper.EntityEvolvablePokemob.func_70636_d(EntityEvolvablePokemob.java:398)
	at pokecube.core.entity.pokemobs.helper.EntityAiPokemob.func_70636_d(EntityAiPokemob.java:812)
	at pokecube.core.entity.pokemobs.helper.EntityHungryPokemob.func_70636_d(EntityHungryPokemob.java:311)
	at pokecube.core.entity.pokemobs.helper.EntityPokemobBase.func_70636_d(EntityPokemobBase.java:596)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2085)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:296)
	at pokecube.core.entity.pokemobs.helper.EntityTameablePokemob.func_70071_h_(EntityTameablePokemob.java:550)
	at pokecube.core.entity.pokemobs.helper.EntityStatsPokemob.func_70071_h_(EntityStatsPokemob.java:555)
	at pokecube.core.entity.pokemobs.helper.EntityEvolvablePokemob.func_70071_h_(EntityEvolvablePokemob.java:404)
	at pokecube.core.entity.pokemobs.helper.EntityMountablePokemob.func_70071_h_(EntityMountablePokemob.java:175)
	at pokecube.core.entity.pokemobs.helper.EntityAiPokemob.func_70071_h_(EntityAiPokemob.java:838)
	at pokecube.core.entity.pokemobs.helper.EntityHungryPokemob.func_70071_h_(EntityHungryPokemob.java:317)
	at pokecube.core.entity.pokemobs.helper.EntityPokemobBase.func_70071_h_(EntityPokemobBase.java:644)
	at net.minecraft.world.World.func_72866_a(World.java:1987)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:840)
	at net.minecraft.world.World.func_72870_g(World.java:1957)

-- Entity being ticked --
Details:
	Entity Type: pokecube_ml:pachirisu (pokecube.core.entity.pokemobs.GenericPokemob417)
	Entity ID: 15
	Entity Name: Pachirisu
	Entity's Exact location: 206.50, 65.00, 146.50
	Entity's Block location: World: (206,64,146), Chunk: (at 14,4,2 in 12,9; contains blocks 192,0,144 to 207,255,159), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, -0.07, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
	World:: net.minecraft.world.WorldServer@15e10db
	Owner:: NULL
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1773)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)

-- Affected level --
Details:
	Level name: goop
	All players: 1 total; [EntityPlayerMP['boxboy'/80, l='goop', x=225.50, y=67.00, z=141.50]]
	Chunk stats: ServerChunkCache: 292 Drop: 0
	Level seed: -4046693936364467535
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (231,64,150), Chunk: (at 7,4,6 in 14,9; contains blocks 224,0,144 to 239,255,159), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 527 game time, 527 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 70572 (now: false), thunder time: 146990 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.11
	Operating System: Windows 7 (x86) version 6.1
	Java Version: 1.8.0_111, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 131265072 bytes (125 MB) / 523501568 bytes (499 MB) up to 523501568 bytes (499 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 3, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.35 Powered by Forge 13.19.1.2199 13 mods loaded, 13 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.11} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11-13.19.1.2199.jar) 
	UCHIJAAAA	forge{13.19.1.2199} [Minecraft Forge] (forge-1.11-13.19.1.2199.jar) 
	UCHIJAAAA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.11.jar) 
	UCHIJAAAA	thutcore{4.3.1} [ThutCore] (thutcore-4.3.1.jar) 
	UCHIJAAAA	pceditmod{1.10.2-2.0.0} [In-game NBTEdit - Pokecube Edition] (Pokecube Core-5.1.1.jar) 
	UCHIJAAAA	pokecube{5.1.1} [Pokécube Core] (Pokecube Core-5.1.1.jar) 
	UCHIJAAAA	pokecube_ml{0.1.0} [Pokecube Model Loader] (Pokecube Core-5.1.1.jar) 
	UCHIJAAAA	pokecube_mobs{2.4.5} [Pokécube Mobs] (Pokecube Mobs-2.4.5.jar) 
	UCHIJAAAA	pokecube_origin{@VERSION@} [Pokecube Origin] (Pokecube Mobs-2.4.5.jar) 
	UCHIJAAAA	thut_wearables{2.1.1} [Thut's Wearables] (thut_wearables-2.1.1.d(1).jar) 
	UCHIJAAAA	thut_bling{1.0.0} [Thut's Bling] (thut_bling-1.0.0.jar) 
	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['boxboy'/80, l='goop', x=225.50, y=67.00, z=141.50]]
	Type: Integrated Server (map_client.txt)

**Comment by P3rf3ctXZer0** [comment]
THE MOD IS OUTDATED AND THUT HAS BEEN BUSY! Dec 2, 2016

**Comment by Thutmose** [comment]
closing this as I don't support 1.11 anymore (only 1.11.2) please re-report this if it occur in 1.10.2, 1.11.2 or 1.12
