### ISSUE TITLE
Crash Pokecube Core-4.31.0.jar

### ISSUE THREAD

**Issue by Snez0kRU** [Thutmose/Pokecube#194]
#### Issue Description:
[12:58:47] [User Authenticator #1/INFO]: UUID of player Snez0k is cb1a0775-4d8f-11e7-b095-f3f7fa000e49
[12:58:48] [Server thread/INFO]: Snez0k[/85.238.103.29:12888] logged in with entity id 1498 in world(0) at (-101.5, 73.0, 250.5)
[12:58:48] [Server thread/INFO]: Welcome Snez0k to the server!
[12:59:02] [Server thread/INFO]: Snez0k has just earned the achievement [Taking Inventory]
[13:00:11] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:715) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) ~[ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NoSuchFieldError: catchAchievements
	at pokecube.alternative.event.EventHandlerCommon.recallPokemon(EventHandlerCommon.java:278) ~[EventHandlerCommon.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_159_EventHandlerCommon_recallPokemon_RecallEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:635) ~[EventBus.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:591) ~[EventBus.class:?]
	at pokecube.core.entity.pokemobs.helper.EntityTameablePokemob.returnToPokecube(EntityTameablePokemob.java:628) ~[EntityTameablePokemob.class:?]
	at pokecube.core.entity.pokemobs.helper.EntityAiPokemob.func_70609_aI(EntityAiPokemob.java:778) ~[EntityAiPokemob.class:?]
	at net.minecraft.entity.EntityLivingBase.onSpongeDeathUpdate(EntityLivingBase.java:3638) ~[sf.class:?]
	at net.minecraft.entity.EntityLivingBase.redirect$causeTrackDeathUpdate$zdb000(EntityLivingBase.java:3628) ~[sf.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:314) ~[sf.class:?]
	at net.minecraft.entity.EntityLiving.func_70030_z(EntityLiving.java:208) ~[sg.class:?]
	at net.minecraft.entity.Entity.func_70071_h_(Entity.java:359) ~[rw.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1932) ~[sf.class:?]
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295) ~[sg.class:?]
	at pokecube.core.entity.pokemobs.helper.EntityTameablePokemob.func_70071_h_(EntityTameablePokemob.java:555) ~[EntityTameablePokemob.class:?]
	at pokecube.core.entity.pokemobs.helper.EntityStatsPokemob.func_70071_h_(EntityStatsPokemob.java:400) ~[EntityStatsPokemob.class:?]
	at pokecube.core.entity.pokemobs.helper.EntityEvolvablePokemob.func_70071_h_(EntityEvolvablePokemob.java:77) ~[EntityEvolvablePokemob.class:?]
	at pokecube.core.entity.pokemobs.helper.EntityMountablePokemob.func_70071_h_(EntityMountablePokemob.java:134) ~[EntityMountablePokemob.class:?]
	at pokecube.core.entity.pokemobs.helper.EntityAiPokemob.func_70071_h_(EntityAiPokemob.java:822) ~[EntityAiPokemob.class:?]
	at pokecube.core.entity.pokemobs.helper.EntityHungryPokemob.func_70071_h_(EntityHungryPokemob.java:317) ~[EntityHungryPokemob.class:?]
	at pokecube.core.entity.pokemobs.helper.EntityPokemobBase.func_70071_h_(EntityPokemobBase.java:596) ~[EntityPokemobBase.class:?]
	at org.spongepowered.common.event.tracking.TrackingUtil.tickEntity(TrackingUtil.java:159) ~[TrackingUtil.class:1.10.2-2281-5.2.0-BETA-2433]
	at net.minecraft.world.WorldServer.redirect$onCallEntityUpdate$zka000(WorldServer.java:2843) ~[ls.class:?]
	at net.minecraft.world.World.func_72866_a(World.java:4072) ~[aid.class:?]
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:839) ~[ls.class:?]
	at net.minecraft.world.World.func_72870_g(World.java:1934) ~[aid.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:6002) ~[aid.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:2185) ~[ls.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709) ~[MinecraftServer.class:?]
	... 4 more
[13:00:11] [Server thread/ERROR]: This crash report has been saved to: /home/minecraft/server/./crash-reports/crash-2017-07-23_13.00.11-server.txt
[13:00:11] [Server thread/INFO]: Stopping server
[13:00:11] [Server thread/INFO]: Saving players
[13:00:11] [Server thread/INFO]: Snez0k lost connection: Server closed
[13:00:11] [Server thread/INFO]: Snez0k left the game
[13:00:11] [Server thread/INFO]: Saving worlds
[13:00:11] [Server thread/INFO]: Redprotect: [World unloaded: world]
[13:00:11] [Server thread/INFO]: Redprotect: [Created folder: /home/minecraft/server/./config/RedProtect/backups/DIM-1]
[13:00:11] [Server thread/INFO]: Redprotect: [World unloaded: DIM-1]
[13:00:11] [Server thread/ERROR]: Exception stopping the server
java.lang.NullPointerException
	at net.minecraft.world.World.handler$onGetWorldInfo$zpa000(World.java:7270) ~[aid.class:?]
	at net.minecraft.world.World.func_72912_H(World.java) ~[aid.class:?]
	at org.spongepowered.common.world.WorldManager.unloadWorld(WorldManager.java:508) ~[WorldManager.class:1.10.2-2281-5.2.0-BETA-2433]
	at net.minecraftforge.common.DimensionManager.setWorld(DimensionManager.java:654) ~[DimensionManager.class:?]
	at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:407) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
[13:00:11] [Server Shutdown Thread/INFO]: Stopping server
[13:00:11] [Server Shutdown Thread/INFO]: Saving players
[13:00:11] [Server Shutdown Thread/INFO]: Saving worlds

Crashreport
Time: 7/23/17 1:00 PM
Description: Ticking entity

java.lang.NoSuchFieldError: catchAchievements
	at pokecube.alternative.event.EventHandlerCommon.recallPokemon(EventHandlerCommon.java:278)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_159_EventHandlerCommon_recallPokemon_RecallEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:635)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:591)
	at pokecube.core.entity.pokemobs.helper.EntityTameablePokemob.returnToPokecube(EntityTameablePokemob.java:628)
	at pokecube.core.entity.pokemobs.helper.EntityAiPokemob.func_70609_aI(EntityAiPokemob.java:778)
	at net.minecraft.entity.EntityLivingBase.onSpongeDeathUpdate(EntityLivingBase.java:3638)
	at net.minecraft.entity.EntityLivingBase.redirect$causeTrackDeathUpdate$zdb000(EntityLivingBase.java:3628)
	at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:314)
	at net.minecraft.entity.EntityLiving.func_70030_z(EntityLiving.java:208)
	at net.minecraft.entity.Entity.func_70071_h_(Entity.java:359)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1932)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at pokecube.core.entity.pokemobs.helper.EntityTameablePokemob.func_70071_h_(EntityTameablePokemob.java:555)
	at pokecube.core.entity.pokemobs.helper.EntityStatsPokemob.func_70071_h_(EntityStatsPokemob.java:400)
	at pokecube.core.entity.pokemobs.helper.EntityEvolvablePokemob.func_70071_h_(EntityEvolvablePokemob.java:77)
	at pokecube.core.entity.pokemobs.helper.EntityMountablePokemob.func_70071_h_(EntityMountablePokemob.java:134)
	at pokecube.core.entity.pokemobs.helper.EntityAiPokemob.func_70071_h_(EntityAiPokemob.java:822)
	at pokecube.core.entity.pokemobs.helper.EntityHungryPokemob.func_70071_h_(EntityHungryPokemob.java:317)
	at pokecube.core.entity.pokemobs.helper.EntityPokemobBase.func_70071_h_(EntityPokemobBase.java:596)
	at org.spongepowered.common.event.tracking.TrackingUtil.tickEntity(TrackingUtil.java:159)
	at net.minecraft.world.WorldServer.redirect$onCallEntityUpdate$zka000(WorldServer.java:2843)
	at net.minecraft.world.World.func_72866_a(World.java:4072)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:839)
	at net.minecraft.world.World.func_72870_g(World.java:1934)
	at net.minecraft.world.World.func_72939_s(World.java:6002)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:2185)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at pokecube.alternative.event.EventHandlerCommon.recallPokemon(EventHandlerCommon.java:278)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_159_EventHandlerCommon_recallPokemon_RecallEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:635)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:591)
	at pokecube.core.entity.pokemobs.helper.EntityTameablePokemob.returnToPokecube(EntityTameablePokemob.java:628)
	at pokecube.core.entity.pokemobs.helper.EntityAiPokemob.func_70609_aI(EntityAiPokemob.java:778)
	at net.minecraft.entity.EntityLivingBase.onSpongeDeathUpdate(EntityLivingBase.java:3638)
	at net.minecraft.entity.EntityLivingBase.redirect$causeTrackDeathUpdate$zdb000(EntityLivingBase.java:3628)
	at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:314)
	at net.minecraft.entity.EntityLiving.func_70030_z(EntityLiving.java:208)
	at net.minecraft.entity.Entity.func_70071_h_(Entity.java:359)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1932)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at pokecube.core.entity.pokemobs.helper.EntityTameablePokemob.func_70071_h_(EntityTameablePokemob.java:555)
	at pokecube.core.entity.pokemobs.helper.EntityStatsPokemob.func_70071_h_(EntityStatsPokemob.java:400)
	at pokecube.core.entity.pokemobs.helper.EntityEvolvablePokemob.func_70071_h_(EntityEvolvablePokemob.java:77)
	at pokecube.core.entity.pokemobs.helper.EntityMountablePokemob.func_70071_h_(EntityMountablePokemob.java:134)
	at pokecube.core.entity.pokemobs.helper.EntityAiPokemob.func_70071_h_(EntityAiPokemob.java:822)
	at pokecube.core.entity.pokemobs.helper.EntityHungryPokemob.func_70071_h_(EntityHungryPokemob.java:317)
	at pokecube.core.entity.pokemobs.helper.EntityPokemobBase.func_70071_h_(EntityPokemobBase.java:596)
	at org.spongepowered.common.event.tracking.TrackingUtil.tickEntity(TrackingUtil.java:159)
	at net.minecraft.world.WorldServer.redirect$onCallEntityUpdate$zka000(WorldServer.java:2843)
	at net.minecraft.world.World.func_72866_a(World.java:4072)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:839)
	at net.minecraft.world.World.func_72870_g(World.java:1934)

-- Entity being ticked --
Details:
	Entity Type: pokecube_ml.Rowlet (pokecube.core.entity.pokemobs.GenericPokemob722)
	Entity ID: 2040
	Entity Name: Rowlet
	Entity's Exact location: -160.57, 66.07, 274.68
	Entity's Block location: World: (-161,66,274), Chunk: (at 15,4,2 in -11,17; contains blocks -176,0,272 to -161,255,287), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.05, -0.01, -0.16
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
	World:: WorldServer{LevelName=world, DimensionId=0, DimensionType=minecraft:overworld}
	Owner:: cb1a0775-4d8f-11e7-b095-f3f7fa000e49
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:6002)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:2185)

-- Affected level --
Details:
	Level name: world
	All players: 1 total; [EntityPlayerMP['Snez0k'/1498, l='world', x=-155.72, y=66.00, z=275.20]]
	Chunk stats: ServerChunkCache: 256 Drop: 0
	Level seed: -1709291549241129208
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-96,64,256), Chunk: (at 0,4,0 in -6,16; contains blocks -96,0,256 to -81,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 2012 game time, 2012 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 10025 (now: false), thunder time: 151598 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false

-- Sponge CauseTracker --
Details:
	Cause Stack: [Empty stack]
Stacktrace:
	at net.minecraft.server.MinecraftServer.handler$onCrashReport$zho000(MinecraftServer.java:3937)
	at net.minecraft.server.MinecraftServer.func_71230_b(MinecraftServer.java:829)
	at net.minecraft.server.dedicated.DedicatedServer.func_71230_b(DedicatedServer.java:361)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:499)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Linux (amd64) version 4.4.0-83-generic
	Java Version: 1.8.0_131, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1179940376 bytes (1125 MB) / 1988624384 bytes (1896 MB) up to 1988624384 bytes (1896 MB)
	JVM Flags: 2 total; -Xmx2048M -Xms2048M
	IntCache: cache: 12, tcache: 94, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2281 27 mods loaded, 27 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2281-universal.jar) 
	UCHIJAAAA	Forge{12.18.3.2281} [Minecraft Forge] (forge-1.10.2-12.18.3.2281-universal.jar) 
	UCHIJAAAA	spongeapi{5.2.0-SNAPSHOT-c675e80} [SpongeAPI] (minecraft.jar) 
	UCHIJAAAA	sponge{1.10.2-2281-5.2.0-BETA-2433} [SpongeForge] (spongeforge-1.10.2-2281-5.2.0-BETA-2433.jar) 
	UCHIJAAAA	catclearlag{0.7.1} [CatClearLag] (CatClearLag-0.7.1.jar) 
	UCHIJAAAA	customnpcs{1.10.2} [CustomNPCs] (CustomNPCs_1.10.2(21jul17).jar) 
	UCHIJAAAA	io.github.hsyyid.essentialcmds{@project.informativeVersion@} [EssentialCmds] (EssentialCmds-1.10.2-8.1.14-universal.jar) 
	UCHIJAAAA	huskycrates{1.5.0} [HuskyCrates] (HuskyCrates-v1.5.0.jar) 
	UCHIJAAAA	ironchest{1.10.2-7.0.11.797} [Iron Chest] (ironchest-1.10.2-7.0.11.797.jar) 
	UCHIJAAAA	io.github.hsyyid.kits{1.7.4} [Kits] (Kits-1.7.4.jar) 
	UCHIJAAAA	permissionsex{2.0-SNAPSHOT-b147} [PermissionsEx] (PermissionsEx-Sponge.jar) 
	UCHIJAAAA	thutcore{3.16.0} [Thut Core] (thutcore-3.16.0.jar) 
	UCHIJAAAA	pceditmod{1.10.2-2.0.0} [In-game NBTEdit - Pokecube Edition] (Pokecube Core-4.31.0.jar) 
	UCHIJAAAA	pokecube{4.31.0} [Pok�cube Core] (Pokecube Core-4.31.0.jar) 
	UCHIJAAAA	pokecube_ml{0.1.0} [Pokecube Model Loader] (Pokecube Core-4.31.0.jar) 
	UCHIJAAAA	pokecube_adventures{4.20.0} [Pok�cube Revival] (Pokecube Revival-4.20.0.jar) 
	UCHIJAAAA	pokecube_mobs{2.10.0} [Pok�cube Mobs] (Pokecube Mobs-2.10.0.jar) 
	UCHIJAAAA	pokecube_moves{@VERSION@} [Pokecube Movess] (Pokecube Mobs-2.10.0.jar) 
	UCHIJAAAA	pokecube_origin{@VERSION@} [Pokecube Origin] (Pokecube Mobs-2.10.0.jar) 
	UCHIJAAAA	pokecube_compat{1.0} [Pokecube Compat] (Pokecube Revival-4.20.0.jar) 
	UCHIJAAAA	pokeplayer{@VERSION} [Pokecube Mystery Dungeon] (Pokecube Revival-4.20.0.jar) 
	UCHIJAAAA	pokecube_alternative{0.0.1} [Pokecube Alternative] (pokecube_alternative-0.0.18.jar) 
	UCHIJAAAA	pjb{0.1.4} [ProjectBorders] (projectborders-5.0.0-0.1.4.jar) 
	UCHIJAAAA	worldedit{6.1.4} [WorldEdit] (worldedit-forge-mc1.10.2-6.1.4-dist.jar) 
	UCHIJAAAA	redprotect{7.2.1} [RedProtect] (RedProtect-Sponge-5.2.0-7.2.1-b141.jar) 
	UCHIJAAAA	totaleconomy{1.5.3} [Total Economy] (TotalEconomy-v1.5.3.jar) 
	Loaded coremods (and transformers): 
SpongeCoremod (spongeforge-1.10.2-2281-5.2.0-BETA-2433.jar)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
	Profiler Position: N/A (disabled)
	Player Count: 1 / 20; [EntityPlayerMP['Snez0k'/1498, l='world', x=-155.72, y=66.00, z=275.20]]
	Is Modded: Definitely; Server brand changed to 'fml,forge,sponge'
	Type: Dedicated Server (map_server.txt)

modlist http://i.imgur.com/8Gk5sQn.png

**Comment by Snez0kRU** [comment]
all because of pokecube-alternative
