### ISSUE TITLE
Description: Ticking entity

### ISSUE THREAD

**Issue by Snez0kRU** [Thutmose/Pokecube#199]
#### Issue Description:
Description: Ticking entity

#### What happens:
java.lang.ClassCastException: pokecube.core.interfaces.capabilities.DefaultPokemob cannot be cast to net.minecraft.entity.Entity
	at pokecube.core.moves.templates.Move_Explode.attack(Move_Explode.java:156)
	at pokecube.core.moves.MovesUtils.doAttack(MovesUtils.java:359)
	at pokecube.core.moves.animations.EntityMoveUse.doMoveUse(EntityMoveUse.java:219)
	at pokecube.core.moves.animations.EntityMoveUse.func_70071_h_(EntityMoveUse.java:187)
	at org.spongepowered.common.event.tracking.TrackingUtil.tickEntity(TrackingUtil.java:159)
	at net.minecraft.world.WorldServer.redirect$onCallEntityUpdate$zkb000(WorldServer.java:2843)
	at net.minecraft.world.World.func_72866_a(World.java:4072)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:839)
	at net.minecraft.world.World.func_72870_g(World.java:1934)
	at net.minecraft.world.World.func_72939_s(World.java:6002)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:2185)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:748)

#### What you expected to happen:
When pokemon use explosion server crashing
Here is Crash report: 
[crash-2017-07-28_13.19.47-server.txt](https://github.com/Thutmose/Pokecube/files/1182715/crash-2017-07-28_13.19.47-server.txt)

#### Steps to reproduce:

1.Download all from modlists
2.Go to expl. pokemon
...

____
#### Affected Versions (Do *not* use "latest"):
![modlist](https://user-images.githubusercontent.com/30385407/28713337-4b6b4808-7397-11e7-8d09-0009c7e72815.png)
Minecraft 1.10.2

**Comment by Thutmose** [comment]
this wlil be fixed in 4.33.5.

current workaround until the release: set explosions to false in pokecube.cfg, that will by-pass the section of code causing this crash.

**Comment by Thutmose** [comment]
fixed in 4.33.5
