### ISSUE TITLE
1.10.2 Crash Report

### ISSUE THREAD

**Issue by Snez0kRU** [Thutmose/Pokecube#203]
#### Issue Description:
Description: Ticking entity

#### What happens:
java.lang.ClassCastException: pokecube.core.interfaces.capabilities.DefaultPokemob cannot be cast to net.minecraft.entity.Entity
	at pokecube.core.database.abilities.f.Forecast.onUpdate(Forecast.java:24)
	at pokecube.core.ai.thread.logicRunnables.LogicMovesUpdates.doServerTick(LogicMovesUpdates.java:101)
	at pokecube.core.entity.pokemobs.helper.EntityAiPokemob.func_70071_h_(EntityAiPokemob.java:803)
	at pokecube.core.entity.pokemobs.helper.EntityHungryPokemob.func_70071_h_(EntityHungryPokemob.java:224)
	at pokecube.core.entity.pokemobs.helper.EntityPokemobBase.func_70071_h_(EntityPokemobBase.java:549)
	at org.spongepowered.common.event.tracking.TrackingUtil.tickEntity(TrackingUtil.java:159)
	at net.minecraft.world.WorldServer.redirect$onCallEntityUpdate$zkb000(WorldServer.java:2843)
	at net.minecraft.world.World.func_72866_a(World.java:4072)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:839)
	at net.minecraft.world.World.func_72870_g(World.java:1934)
	at net.minecraft.world.World.func_72939_s(World.java:6002)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:2185)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:748)

#### What you expected to happen:
Didn't know

#### Steps to reproduce:
[crash-2017-07-29_17.09.22-server.txt](https://github.com/Thutmose/Pokecube/files/1184991/crash-2017-07-29_17.09.22-server.txt)

____
#### Affected Versions (Do *not* use "latest"):
![21312321321321](https://user-images.githubusercontent.com/30385407/28745223-628ae4d6-747c-11e7-8290-3af87787bbbf.png)

**Comment by Thutmose** [comment]
I will get this fixed asap, I think I need to upload a new version of pokecube core and thutcore for 1.10.2 as well.

**Comment by Thutmose** [comment]
this commit fixes it, I need to also prepare the new pokecube core and thutcore for 1.10.2 before I can release it though, the crash is caused by a castform.

https://github.com/Thutmose/Pokecube-Mobs/commit/1ff1a24e0551c0b48fa3719244f04daaf7b7e43f
