### ISSUE TITLE
Crash - java.lang.ClassCastException: pokecube.core.interfaces.capabilities.DefaultPokemob cannot be cast to net.minecraft.entity.Entity

### ISSUE THREAD

**Issue by Iiridayn** [Thutmose/Pokecube#212]
#### Issue Description:

Seems the same error as #111, but I can't reopen that one. Pokecube crashes the server with "java.lang.ClassCastException: pokecube.core.interfaces.capabilities.DefaultPokemob cannot be cast to net.minecraft.entity.Entity".

#### Modlist:

Forge 1.10.2-12.18.3.2185

`ls mods | cat`
```
[1.10.2]ForgeCreeperHeal-2.0.1.jar
[1.10.2]UncraftingTable-1.6.3.jar
AppleSkin-mc1.10.2-1.0.7.jar
autowalk-1.10.2-1.2.jar
BackTools-1.10.2-6.0.0.jar
base-1.10.2-1.4.0.jar
BaseMetals_1.10.2-2.4.0.11.jar
Baubles-1.10.2-1.3.11.jar
BaublesHud-1.10.2-3.2.0.jar
baublesstuff-3.0.2.jar
BetterBuildersWands-1.10.2-0.11.1.220+f8232fe.jar
Bookshelf-1.10.2-1.4.4.347.jar
Botania r1.9-341.jar
CapabilityProxy-1.10.2-1.0.0.jar
Chameleon-1.10.2-2.3.0.jar
Clumps-1.0.5.jar
CodeChickenCore-1.10.2-2.4.1.102-universal.jar
CodeChickenLib-1.10.2-2.5.9.283-universal.jar
ColossalChests-1.10.2-1.6.0.jar
CookingForBlockheads_1.10.2-4.2.45.jar
CraftingTweaks_1.10.2-6.1.16.jar
CyclopsCore-1.9.4-0.10.7.jar
DarkUtilities-1.1.8.finalrc2.jar
DeathCounter-1.10.2-1.0.0.jar
DeathQuotes-1.2.0-mc1.9to1.10.2-forge.jar
DrZhark's Mo'Creatures Mod-10.0.6.jar
EnderStorage-1.10.2-2.2.1.106-universal.jar
EnergySynergy-1.10.2-1.1.3.jar
extrautils2-1.10.2-1.5.1.jar
FasterLadderClimbing-1.9.4-0.1-122.jar
FastLeafDecay-v11.jar
ForgivingVoid_1.10.2-1.0.1.jar
geneticsreborn-mc1.10.2-v1.05.jar
hats
Hats-1.10.2-6.0.0.jar
Hwyla-1.8.17-B31_1.10.2.jar
iChunUtil-1.10.2-6.4.0.jar
InventoryTweaks-1.61-58.jar
IronBackpacks-1.10.2-2.2.28.jar
itemscroller-1.10.2-0.11.0.jar
jehc-1.10.2-1.2.2.jar
jei_1.10.2-3.14.7.419.jar
journeymap-1.10.2-5.4.7.jar
JustAFewFish-1.5.3_for_1.10.2.jar
JustEnoughResources-1.10.2-0.5.8.98.jar
LootBags-1.10.2-2.3.9.jar
Mantle-1.10.2-1.1.5.jar
MCA-1.10.2-5.2.3-universal.jar
mod_list.json
modnametooltip_1.10.2-1.6.0.jar
ModularPowersuits-1.10.2-1.2.124.jar
MorePlayerModels_1.10.2(16jul17).jar
Morpheus-1.10.2-3.1.13.jar
natura-1.10.2-4.1.0.73.jar
nethercore-1.10.2-2.0.3.jar
NetherPortalFix_1.10.2-3.3.4.jar
OreSpawn_1.10.2-1.1.0.jar
Pam's HarvestCraft 1.10.2j.jar
Pokecube Core-4.33.5.jar
Pokecube Mobs-2.12.0.jar
Pokecube Revival-4.22.1.jar
PortalGun-1.10.2-6.0.1.jar
RadixCore-1.10.2-2.1.3-universal.jar
RoguelikeDungeons-1.10.2-1.5.9.jar
Scannable-MC1.10.2-1.4.1.23.jar
SophisticatedWolves-3.6.5.jar
StorageDrawers-1.10.2-3.7.10.jar
TConstruct-1.10.2-2.6.5.jar
thutcore-3.16.1.jar
Tinkers' Addons-1.10.2-1.0.6.jar
Translocators-1.10.2-2.1.4.55-universal.jar
ultimate_unicorn_mod-1.10.2-1.5.13.jar
VanillaTeleporter-1.10.2-1.6.2.jar
VeinMiner-1.9-0.38.1.618+5587fc8.jar
VillageNames-1.10.2-1.1a.jar
WailaHarvestability-mc1.10.2-1.1.10.jar
woot-1.10.2-1.4.1.jar
```

#### What happens:

Short log:

```
Description: Ticking entity

java.lang.ClassCastException: pokecube.core.interfaces.capabilities.DefaultPokemob cannot be cast to net.minecraft.entity.Entity
        at pokecube.core.database.abilities.f.Forecast.onUpdate(Forecast.java:24)
        at pokecube.core.ai.thread.logicRunnables.LogicMovesUpdates.doServerTick(LogicMovesUpdates.java:101)
        at pokecube.core.entity.pokemobs.helper.EntityAiPokemob.func_70071_h_(EntityAiPokemob.java:803)
        at pokecube.core.entity.pokemobs.helper.EntityHungryPokemob.func_70071_h_(EntityHungryPokemob.java:224)
        at pokecube.core.entity.pokemobs.helper.EntityPokemobBase.func_70071_h_(EntityPokemobBase.java:549)
        at net.minecraft.world.World.func_72866_a(World.java:1964)
        at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:839)
        at net.minecraft.world.World.func_72870_g(World.java:1934)
        at net.minecraft.world.World.func_72939_s(World.java:1750)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
        at java.lang.Thread.run(Thread.java:748)
```

#### What you expected to happen:

No crash.

#### Steps to reproduce:

Unknown. Willing to send zip of world and mods if you can promise confidentiality and to only use it to diagnose the issue. Has crashed 3 times with the same crash now, so should be reproducible.

____
#### Affected Versions (Do *not* use "latest"):

- Pokecube Core: 4.33.5
- Pokecube Revival (if applicable): 4.22.1
- Pokecube Mobs (if applicable): 2.12.0
- Minecraft: 1.10.2
- Forge:1.10.2-12.18.3.2185

**Comment by Thutmose** [comment]
Your version of pokecube mobs is rather outdated, update that and see if it still crashes, spawn a castform with a command block, if it doesn't crash immediately, then it is fixed.

**Comment by Thutmose** [comment]
#111 is completely unrelated

**Comment by Iiridayn** [comment]
Yep, updated Core, Revival, Mobs, and thutcore and server no longer crashes. Have emailed new zip file with pokecube updates to all server users to unzip into their mods folder. Do you know of a simpler and reliable way to manage n user mod updates?

**Comment by Thutmose** [comment]
If all your mods are on curseforge, you can use a modpack with the twitch client and update that, then have them use that.

**Comment by Iiridayn** [comment]
So kinda like Feed The Beast's user modpacks - download another client. Thanks, I'll look into it :/.

**Comment by Thutmose** [comment]
Ya, I mostly like twitch launcher as the modpack I need to upload is only a few kB or so, and curseforge also gives me an idea of how many downloads the mod gets.

I think the twitch launcher might work for FTB packs?
