### ISSUE TITLE
CRASHING HELP

### ISSUE THREAD

**Issue by BlearOsprey1107** [Thutmose/Pokecube#217]
Help me when i play the mod when i play the world it crashes then i can't play the game i can't give the log because it too long help D:

**Comment by BlearOsprey1107** [comment]
here is the log

**Comment by BlearOsprey1107** [comment]
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 9/27/17 11:10 AM
Description: Ticking entity

java.lang.IllegalAccessError: tried to access field net.minecraft.pathfinding.PathPoint.field_75840_j from class thut.api.pathing.PathPoint
	at thut.api.pathing.PathPoint.<init>(PathPoint.java:85)
	at thut.api.pathing.ThutPathFinder.openPoint(ThutPathFinder.java:589)
	at thut.api.pathing.ThutPathFinder.createEntityPathTo(ThutPathFinder.java:206)
	at thut.api.pathing.ThutPathFinder.createEntityPathTo(ThutPathFinder.java:234)
	at thut.api.pathing.Paths.getPathHeapToEntity(Paths.java:32)
	at pokecube.core.ai.utils.PokeNavigator.func_75494_a(PokeNavigator.java:166)
	at pokecube.core.ai.utils.PokeNavigator.func_75497_a(PokeNavigator.java:284)
	at pokecube.core.ai.thread.aiRunnables.AIMate.tryFindMate(AIMate.java:257)
	at pokecube.core.ai.thread.aiRunnables.AIMate.doMainThreadTick(AIMate.java:77)
	at thut.api.entity.ai.AIThreadManager$AIStuff.runServerThreadTasks(AIThreadManager.java:63)
	at pokecube.core.entity.pokemobs.helper.EntityAiPokemob.func_70626_be(EntityAiPokemob.java:758)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2346)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:178)
	at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:43)
	at pokecube.core.entity.pokemobs.helper.EntityEvolvablePokemob.func_70636_d(EntityEvolvablePokemob.java:27)
	at pokecube.core.entity.pokemobs.helper.EntityAiPokemob.func_70636_d(EntityAiPokemob.java:608)
	at pokecube.core.entity.pokemobs.helper.EntityPokemobBase.func_70636_d(EntityPokemobBase.java:450)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2166)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at pokecube.core.entity.pokemobs.helper.EntityTameablePokemob.func_70071_h_(EntityTameablePokemob.java:202)
	at pokecube.core.entity.pokemobs.helper.EntityMountablePokemob.func_70071_h_(EntityMountablePokemob.java:68)
	at pokecube.core.entity.pokemobs.helper.EntityAiPokemob.func_70071_h_(EntityAiPokemob.java:625)
	at pokecube.core.entity.pokemobs.helper.EntityPokemobBase.func_70071_h_(EntityPokemobBase.java:490)
	at net.minecraft.world.World.func_72866_a(World.java:1984)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:833)
	at net.minecraft.world.World.func_72870_g(World.java:1946)
	at net.minecraft.world.World.func_72939_s(World.java:1754)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:614)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at thut.api.pathing.PathPoint.<init>(PathPoint.java:85)
	at thut.api.pathing.ThutPathFinder.openPoint(ThutPathFinder.java:589)
	at thut.api.pathing.ThutPathFinder.createEntityPathTo(ThutPathFinder.java:206)
	at thut.api.pathing.ThutPathFinder.createEntityPathTo(ThutPathFinder.java:234)
	at thut.api.pathing.Paths.getPathHeapToEntity(Paths.java:32)
	at pokecube.core.ai.utils.PokeNavigator.func_75494_a(PokeNavigator.java:166)
	at pokecube.core.ai.utils.PokeNavigator.func_75497_a(PokeNavigator.java:284)
	at pokecube.core.ai.thread.aiRunnables.AIMate.tryFindMate(AIMate.java:257)
	at pokecube.core.ai.thread.aiRunnables.AIMate.doMainThreadTick(AIMate.java:77)
	at thut.api.entity.ai.AIThreadManager$AIStuff.runServerThreadTasks(AIThreadManager.java:63)
	at pokecube.core.entity.pokemobs.helper.EntityAiPokemob.func_70626_be(EntityAiPokemob.java:758)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2346)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:178)
	at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:43)
	at pokecube.core.entity.pokemobs.helper.EntityEvolvablePokemob.func_70636_d(EntityEvolvablePokemob.java:27)
	at pokecube.core.entity.pokemobs.helper.EntityAiPokemob.func_70636_d(EntityAiPokemob.java:608)
	at pokecube.core.entity.pokemobs.helper.EntityPokemobBase.func_70636_d(EntityPokemobBase.java:450)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2166)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at pokecube.core.entity.pokemobs.helper.EntityTameablePokemob.func_70071_h_(EntityTameablePokemob.java:202)
	at pokecube.core.entity.pokemobs.helper.EntityMountablePokemob.func_70071_h_(EntityMountablePokemob.java:68)
	at pokecube.core.entity.pokemobs.helper.EntityAiPokemob.func_70071_h_(EntityAiPokemob.java:625)
	at pokecube.core.entity.pokemobs.helper.EntityPokemobBase.func_70071_h_(EntityPokemobBase.java:490)
	at net.minecraft.world.World.func_72866_a(World.java:1984)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:833)
	at net.minecraft.world.World.func_72870_g(World.java:1946)

-- Entity being ticked --
Details:
	Entity Type: pokecube_ml:rattata (pokecube.core.entity.pokemobs.GenericPokemob19)
	Entity ID: 14
	Entity Name: Rattata
	Entity's Exact location: -862.50, 4.00, -364.50
	Entity's Block location: World: (-863,4,-365), Chunk: (at 1,0,3 in -54,-23; contains blocks -864,0,-368 to -849,255,-353), Region: (-2,-1; contains chunks -64,-32 to -33,-1, blocks -1024,0,-512 to -513,255,-1)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
	World:: net.minecraft.world.WorldServer@3bcb85
	Owner:: NULL
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1754)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:614)

-- Affected level --
Details:
	Level name: Pokecube mod
	All players: 1 total; [EntityPlayerMP['minealif'/34, l='Pokecube mod', x=-880.50, y=4.00, z=-358.50]]
	Chunk stats: ServerChunkCache: 625 Drop: 0
	Level seed: 3091555669980555880
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-879,4,-362), Chunk: (at 1,0,6 in -55,-23; contains blocks -880,0,-368 to -865,255,-353), Region: (-2,-1; contains chunks -64,-32 to -33,-1, blocks -1024,0,-512 to -513,255,-1)
	Level time: 483 game time, 483 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 99577 (now: false), thunder time: 94630 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.1
	Operating System: Windows 10 (x86) version 10.0
	Java Version: 1.8.0_131, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 96845136 bytes (92 MB) / 523501568 bytes (499 MB) up to 523501568 bytes (499 MB)
	JVM Flags: 10 total; -XX:HeapDumpPath=ThisTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M -Xms256M -Xmn128M -XX:+UseConcMarkSweepGC -XX:-UseAdaptiveSizePolicy -XX:+CMSParallelRemarkEnabled -XX:+ParallelRefProcEnabled -XX:+CMSClassUnloadingEnabled -XX:+UseCMSInitiatingOccupancyOnly
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.41 Powered by Forge 14.22.1.2485 15 mods loaded, 15 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                  | Version      | Source                        | Signature                                |
	|:--------- |:------------------- |:------------ |:----------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft           | 1.12.1       | minecraft.jar                 | None                                     |
	| UCHIJAAAA | mcp                 | 9.19         | minecraft.jar                 | None                                     |
	| UCHIJAAAA | FML                 | 8.0.99.99    | forge-1.12.1-14.22.1.2485.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge               | 14.22.1.2485 | forge-1.12.1-14.22.1.2485.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | mercurius_updater   | 1.0          | MercuriusUpdater-1.12.1.jar   | None                                     |
	| UCHIJAAAA | thutcore            | 5.11.1       | thutcore-5.11.1.jar           | None                                     |
	| UCHIJAAAA | pceditmod           | 1.10.2-2.0.0 | Pokecube Core-6.21.2.jar      | None                                     |
	| UCHIJAAAA | pokecube            | 6.21.2       | Pokecube Core-6.21.2.jar      | None                                     |
	| UCHIJAAAA | pokecube_ml         | 0.1.0        | Pokecube Core-6.21.2.jar      | None                                     |
	| UCHIJAAAA | thut_wearables      | 3.1.1        | thut_wearables-3.1.1.jar      | None                                     |
	| UCHIJAAAA | pokecube_adventures | 6.11.2       | Pokecube Revival-6.11.2.jar   | None                                     |
	| UCHIJAAAA | pokecube_mobs       | 2.14.10      | Pokecube Mobs-2.14.10.jar     | None                                     |
	| UCHIJAAAA | pokecube_moves      | @VERSION@    | Pokecube Mobs-2.14.10.jar     | None                                     |
	| UCHIJAAAA | pokecube_origin     | @VERSION@    | Pokecube Mobs-2.14.10.jar     | None                                     |
	| UCHIJAAAA | pokecube_compat     | 1.0          | Pokecube Revival-6.11.2.jar   | None                                     |

	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['minealif'/34, l='Pokecube mod', x=-880.50, y=4.00, z=-358.50]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Thutmose** [comment]
hmm, for now, try reverting to forge 2475, i wonder if forge broke something in a recent version.

**Comment by Thutmose** [comment]
This should be fixed in the versions I just uploaded, Pokecube Core 6.21.3 and ThutCore 5.11.2

**Comment by BlearOsprey1107** [comment]
Still crash but i can play a bit
