### ISSUE TITLE
CTD when hovering over pokedex in inventory

### ISSUE THREAD

**Issue by st753m** [Thutmose/Pokecube#235]
#### Issue Description:

When I hover over the pokedex item in my inventory or a chest, the game crashes to desktop immediately every time.
Also, when I looked up the pokedex in JEI, the name was messed up but didn't crash me.  Instead of a name, there's red text called "Tooltip Error, see log"

I think this is the part of the log they're talking about?  In logs/latest.log:

[11:15:23] [main/ERROR]: Failed to get tooltip: 1xitem.pokedex@0 pokecube:pokedex
java.lang.NullPointerException: null
	at thut.wearables.compat.baubles.Compat$WearableWrapper.getBaubleType(Compat.java:105) ~[Compat$WearableWrapper.class:?]
	at baubles.client.ClientEventHandler.tooltipEvent(ClientEventHandler.java:41) ~[ClientEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_274_ClientEventHandler_tooltipEvent_ItemTooltipEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179) ~[EventBus.class:?]
	at net.minecraftforge.event.ForgeEventFactory.onItemTooltip(ForgeEventFactory.java:284) ~[ForgeEventFactory.class:?]
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:889) ~[aip.class:?]
	at mezz.jei.plugins.vanilla.ingredients.ItemStackRenderer.getTooltip(ItemStackRenderer.java:39) [ItemStackRenderer.class:?]
	at mezz.jei.plugins.vanilla.ingredients.ItemStackRenderer.getTooltip(ItemStackRenderer.java:20) [ItemStackRenderer.class:?]
	at mezz.jei.ingredients.IngredientInformation.getTooltipStrings(IngredientInformation.java:32) [IngredientInformation.class:?]
	at mezz.jei.ingredients.IngredientListElement.getTooltipStrings(IngredientListElement.java:142) [IngredientListElement.class:?]
	at mezz.jei.ingredients.IngredientFilter$$Lambda$710/1409362574.getStrings(Unknown Source) [IngredientFilter.class:?]
	at mezz.jei.ingredients.IngredientFilter.addIngredient(IngredientFilter.java:113) [IngredientFilter.class:?]
	at mezz.jei.ingredients.IngredientFilter.addIngredients(IngredientFilter.java:89) [IngredientFilter.class:?]
	at mezz.jei.startup.JeiStarter.start(JeiStarter.java:73) [JeiStarter.class:?]
	at mezz.jei.startup.ProxyCommonClient.loadComplete(ProxyCommonClient.java:122) [ProxyCommonClient.class:?]
	at mezz.jei.JustEnoughItems.loadComplete(JustEnoughItems.java:54) [JustEnoughItems.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:606) [FMLModContainer.class:?]
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [guava-21.0.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [guava-21.0.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [guava-21.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) [guava-21.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231) [LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [guava-21.0.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [guava-21.0.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [guava-21.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) [guava-21.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148) [LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:727) [Loader.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:352) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[11:15:23] [main/INFO]: Building ingredient filter took 672.7 ms

The Crash Report: 
[crash-2017-11-29_11.07.32-client.txt](https://github.com/Thutmose/Pokecube/files/1514507/crash-2017-11-29_11.07.32-client.txt)

#### Steps to reproduce:

1. Have a pokedex in your inventory or chest
2. Try to hover the mouse cursor over the pokedex

____
#### Affected Versions (Do *not* use "latest"):

- Pokecube Core:6.26.3
- Pokecube Revival (if applicable): 6.13.9
- Pokecube Mobs (if applicable): 4.1.4
- Minecraft: 1.12.2
- Forge: 14.23.1.2556
Also, since they might be relevant:
- Thut Wearables: 3.1.2
- Thut Core: 5.11.10
- Botania: r1.10-350
- Baubles: 1.12-1.5.1

**Comment by Thutmose** [comment]
Seems to be a bug in wearables' baubles support,I will see about getting a fix for that out asap

**Comment by Thutmose** [comment]
This should be fixed in thutwearables 3.1.3, please let me know if it fixes it for you, it should now instead just say "type.null" or something in the pokedex's tooltip, please reopen issue if it isn't fixed then.
