### ISSUE TITLE
Custom Npc's Crash 1.12.2

### ISSUE THREAD

**Issue by AnonymousXXI** [Thutmose/Pokecube#276]
#### Issue Description:
When I try to edit a NPC created by Custom NPCs with the trainer editor I crash. 

-----------------------------------------------------
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at net.minecraft.client.gui.GuiButton.func_191745_a(GuiButton.java:66)
	at pokecube.adventures.client.gui.trainer.EditTrainerPage$PokemobEntry.func_192634_a(EditTrainerPage.java:76)
	at net.minecraft.client.gui.GuiListExtended.func_192637_a(SourceFile:25)
	at net.minecraft.client.gui.GuiSlot.func_192638_a(GuiSlot.java:483)
	at pokecube.core.client.gui.helper.ScrollGui.func_148128_a(ScrollGui.java:121)
	at pokecube.adventures.client.gui.trainer.ListPage.func_73863_a(ListPage.java:61)
	at pokecube.adventures.client.gui.trainer.EditTrainerPage.func_73863_a(EditTrainerPage.java:405)
	at pokecube.adventures.client.gui.trainer.GuiEditTrainer.func_73863_a(GuiEditTrainer.java:170)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:368)
	at sun.reflect.GeneratedMethodAccessor48.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at Reflector.callVoid(Reflector.java:636)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1454)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

------------------------------------------------------
#### What happens:
I right click on the mob with the Trainer editor and the game crashes.

#### What you expected to happen:
I'll be able to edit the NPCs team and save them.

#### Steps to reproduce:

1. Create a mob using the wand from Custom NPCs
2. Try to activate the Trainer Editor.
...

____
#### Affected Versions (Do *not* use "latest"):

- Pokecube Core: pokecube-core-1.12.2-6.36.7
- Pokecube Revival (if applicable): pokecube-revival-1.12.2-6.14.15
- Pokecube Mobs (if applicable): pokecube-mobs-1.12.2-4.7.0
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.2.2624

3 other small questions. 

Is it possible to get lava from Camerupt?

When editing a normal trainer (ones from your mod) , where do I get the skins to put under the URL skin option in the Trainer Editor? All the links I tried are too big to fit in the space provided.

How exactly do Daycare blocks work? I looked online and couldn't find anything.

**Comment by Thutmose** [comment]
I will look into this crash when I have time, it might take me some time, as I have quite a bit of other work I need to do, so don't have much time for minecraft, I should have plenty of time starting next month though.

for the questions:

You should be able to milk female numels and camerupts for lava.

I normally make an imgur mirror for the skin (ie upload it to imgur), then link the png from that.

you put emeralds in the slots in the daycare (top slot takes emerald blocks, bottom takes shards, it automatically distributes shards to bottom if you stick a block in the top), it then slowly consumes the shards and gives exp to the pokemobs within 4 blocks of it

**Comment by AnonymousXXI** [comment]
Thanks , is there any command to spawn in a trainer?

**Comment by Thutmose** [comment]
there is an item called a trainer editor, if you shift right click with it, it will spawn a trainer
