### ISSUE TITLE
Illegal Code Issue

### ISSUE THREAD

**Issue by DPxKnightxZero** [Thutmose/Pokecube#33]
#### Issue Description:
java.lang.IllegalArgumentException: Cannot get property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[north, south, west, east]} as it does not exist in BlockStateContainer{block=pokecube:tradingtable, properties=[facing, tmc]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:197)
	at pokecube.core.blocks.tradingTable.BlockTradingTable.func_176201_c(BlockTradingTable.java:141)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:95)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:277)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(ChunkRenderWorker.java:118)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(ChunkRenderWorker.java:46)
	at java.lang.Thread.run(Unknown Source)

#### What happens:
Illegal Code for Forge Version

#### What you expected to happen:
Not sure

#### Steps to reproduce:

1. Download MultiMC and add this instance to your instance tree [PZ]-[1.9.4]-Eclipse-r3
2. https://www.dropbox.com/s/yhy39ncqcdeffwo/%5BPZ%5D-%5B1.9.4%5D-Eclipse-r3.zip?dl=1
3. Launch Game and load the pre-existing world 
...

____
#### Affected Versions (Do *not* use "latest"):

- Pokecube Core: 3.2.3
- Pokecube Revival (if applicable):
- Pokecube Mobs (if applicable): 2.1.0
- Pokecube - Thutcore : 3.1.2
- Minecraft: 1.9.4
- Forge: FML: MCP 9.28 Powered by Forge 12.17.0.1968 Optifine OptiFine_1.9.4_HD_U_B6 10 mods loaded

**Comment by Thutmose** [comment]
you seem to somehow have a corrupted block in that save.

**Comment by Thutmose** [comment]
Try removing optifine, see if that fixes the problem.
