### ISSUE TITLE
[1.9.4] Pokemon exception during loading

### ISSUE THREAD

**Issue by XileForce** [Thutmose/Pokecube#53]
Recently noticed this happening several times in the server console. It told me to tell you so here I am!

06/22/2016 14:52:37
14:52:37[net.minecraft.crash.CrashReport:func_85057_a:290]: Negative index in crash report handler (0/13)
Server thread/ERROR - FML 06/22/2016 14:52:37
14:52:37An Entity pokecube_ml.Gligar(pokecube.core.entity.pokemobs.GenericPokemob207) has thrown an exception during loading, its state cannot be restored. Report this to the mod author
Console 06/22/2016 14:52:37
14:52:37net.minecraft.util.ReportedException: Loading entity NBT
at net.minecraft.entity.Entity.func_70020_e(Entity.java:1678) ~[rr.class:?]
at net.minecraft.entity.EntityList.func_75615_a(EntityList.java:174) [rt.class:?]
at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_186053_a(AnvilChunkLoader.java:559) [ast.class:?]
at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_186054_a(AnvilChunkLoader.java:518) [ast.class:?]
at net.minecraft.tileentity.MobSpawnerBaseLogic.func_98278_g(MobSpawnerBaseLogic.java:102) [ahk.class:?]
at net.minecraft.tileentity.TileEntityMobSpawner.func_73660_a(SourceFile:62) [aqk.class:?]
at net.minecraft.world.World.func_72939_s(World.java:1797) [aht.class:?]
at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:618) [lq.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:707) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:385) [lb.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:611) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:469) [MinecraftServer.class:?]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_92]
Caused by: java.lang.NullPointerException

Forge 1968
Pokecube core 3.2.13
Pokecube mobs 2.1.2
Pokecube revival 3.2.5

**Comment by Thutmose** [comment]
odd, not sure what is going on there, if it happens again, let me know how you get it to happen.

**Comment by Thutmose** [comment]
This crash shouldn't occur anymore, re-open if it does.
