### ISSUE TITLE
[1.9.4] Failed to save chunk

### ISSUE THREAD

**Issue by XileForce** [Thutmose/Pokecube#55]
Now whenever my server starts and stops I get this message as well as randomly during its running. Only have noticed it since the last update. but it could be coincidence.

[23:03:06] [Server thread/ERROR]: Failed to save chunk
net.minecraft.util.ReportedException: Saving entity NBT
	at net.minecraft.entity.Entity.func_189511_e(Entity.java:1582) ~[rr.class:?]
	at net.minecraft.entity.Entity.func_70039_c(Entity.java:1491) ~[rr.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:322) ~[ast.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:173) [ast.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:202) [lp.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73156_b(ChunkProviderServer.java:270) [lp.class:?]
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:201) [lq.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:696) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:385) [lb.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:611) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:469) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_92]
Caused by: java.lang.NullPointerException
	at net.minecraft.village.MerchantRecipe.func_77395_g(SourceFile:129) ~[ahg.class:?]
	at net.minecraft.village.MerchantRecipeList.func_77202_a(SourceFile:132) ~[ahh.class:?]
	at pokecube.adventures.entity.trainers.EntityTrainer.func_70014_b(EntityTrainer.java:990) ~[EntityTrainer.class:?]
	at net.minecraft.entity.Entity.func_189511_e(Entity.java:1553) ~[rr.class:?]
	... 11 more
[23:03:19]

Forge 1977
Pokecube core 3.3
Pokecube mobs 2.1.2
Pokecube revival 3.3

**Comment by XileForce** [comment]
I ran a pokecube kill all command and havent seen it since. may have just been a bugged out trainer.

**Comment by Thutmose** [comment]
That should be fixed in the next version.

**Comment by Thutmose** [comment]
fixed in 3.3.1
