### ISSUE TITLE
[1.9.4] Pokemob AI Thread Error

### ISSUE THREAD

**Issue by XileForce** [Thutmose/Pokecube#80]
I've no clue what this means or what caused it, but once it started it was endless. as you can see from the timestamps. the log file was nearly 20mbs. the players on the server didnt seem to notice but I figured id report it in case its more than just a random bug.

[18:46:26] [Server thread/INFO] [STDERR/]: [pokecube.core.ai.thread.PokemobAIThread$AIStuff:tick:80]: java.lang.IllegalArgumentException: Comparison method violates its general contract!
[18:46:26] [Server thread/INFO] [STDERR/]: [pokecube.core.ai.thread.PokemobAIThread$AIStuff:tick:80]: 	at java.util.TimSort.mergeLo(Unknown Source)
[18:46:26] [Server thread/INFO] [STDERR/]: [pokecube.core.ai.thread.PokemobAIThread$AIStuff:tick:80]: 	at java.util.TimSort.mergeAt(Unknown Source)
[18:46:26] [Server thread/INFO] [STDERR/]: [pokecube.core.ai.thread.PokemobAIThread$AIStuff:tick:80]: 	at java.util.TimSort.mergeCollapse(Unknown Source)
[18:46:26] [Server thread/INFO] [STDERR/]: [pokecube.core.ai.thread.PokemobAIThread$AIStuff:tick:80]: 	at java.util.TimSort.sort(Unknown Source)
[18:46:26] [Server thread/INFO] [STDERR/]: [pokecube.core.ai.thread.PokemobAIThread$AIStuff:tick:80]: 	at java.util.Arrays.sort(Unknown Source)
[18:46:26] [Server thread/INFO] [STDERR/]: [pokecube.core.ai.thread.PokemobAIThread$AIStuff:tick:80]: 	at thut.api.maths.Matrix3.doTileCollision(Matrix3.java:688)
[18:46:26] [Server thread/INFO] [STDERR/]: [pokecube.core.ai.thread.PokemobAIThread$AIStuff:tick:80]: 	at thut.api.maths.Matrix3.doTileCollision(Matrix3.java:863)
[18:46:26] [Server thread/INFO] [STDERR/]: [pokecube.core.ai.thread.PokemobAIThread$AIStuff:tick:80]: 	at thut.api.pathing.ThutPathFinder.isEmpty(ThutPathFinder.java:539)
[18:46:26] [Server thread/INFO] [STDERR/]: [pokecube.core.ai.thread.PokemobAIThread$AIStuff:tick:80]: 	at thut.api.pathing.ThutPathFinder.isSafe(ThutPathFinder.java:559)
[18:46:26] [Server thread/INFO] [STDERR/]: [pokecube.core.ai.thread.PokemobAIThread$AIStuff:tick:80]: 	at thut.api.pathing.ThutPathFinder.findOptions(ThutPathFinder.java:310)
[18:46:26] [Server thread/INFO] [STDERR/]: [pokecube.core.ai.thread.PokemobAIThread$AIStuff:tick:80]: 	at thut.api.pathing.JPSPather.findOptions(JPSPather.java:86)
[18:46:26] [Server thread/INFO] [STDERR/]: [pokecube.core.ai.thread.PokemobAIThread$AIStuff:tick:80]: 	at thut.api.pathing.ThutPathFinder.getPoint(ThutPathFinder.java:404)
[18:46:26] [Server thread/INFO] [STDERR/]: [pokecube.core.ai.thread.PokemobAIThread$AIStuff:tick:80]: 	at thut.api.pathing.JPSPather.getSubPath(JPSPather.java:133)
[18:46:26] [Server thread/INFO] [STDERR/]: [pokecube.core.ai.thread.PokemobAIThread$AIStuff:tick:80]: 	at thut.api.pathing.ThutPathFinder.addToPath(ThutPathFinder.java:111)
[18:46:26] [Server thread/INFO] [STDERR/]: [pokecube.core.ai.thread.PokemobAIThread$AIStuff:tick:80]: 	at thut.api.pathing.ThutPathFinder.createEntityPathTo(ThutPathFinder.java:208)
[18:46:26] [Server thread/INFO] [STDERR/]: [pokecube.core.ai.thread.PokemobAIThread$AIStuff:tick:80]: 	at thut.api.pathing.ThutPathFinder.createEntityPathTo(ThutPathFinder.java:232)
[18:46:26] [Server thread/INFO] [STDERR/]: [pokecube.core.ai.thread.PokemobAIThread$AIStuff:tick:80]: 	at thut.api.pathing.Paths.getPathHeapToEntity(Paths.java:73)
[18:46:26] [Server thread/INFO] [STDERR/]: [pokecube.core.ai.thread.PokemobAIThread$AIStuff:tick:80]: 	at pokecube.core.ai.utils.PokeNavigator.func_75494_a(PokeNavigator.java:187)
[18:46:26] [Server thread/INFO] [STDERR/]: [pokecube.core.ai.thread.PokemobAIThread$AIStuff:tick:80]: 	at pokecube.core.ai.thread.aiRunnables.AIAttack.run(AIAttack.java:121)
[18:46:26] [Server thread/INFO] [STDERR/]: [pokecube.core.ai.thread.PokemobAIThread$AIStuff:tick:80]: 	at pokecube.core.ai.thread.PokemobAIThread$AIStuff.tick(PokemobAIThread.java:71)
[18:46:26] [Server thread/INFO] [STDERR/]: [pokecube.core.ai.thread.PokemobAIThread$AIStuff:tick:80]: 	at pokecube.core.ai.thread.PokemobAIThread$AIStuff.runServerThreadTasks(PokemobAIThread.java:52)
[18:46:26] [Server thread/INFO] [STDERR/]: [pokecube.core.ai.thread.PokemobAIThread$AIStuff:tick:80]: 	at pokecube.core.entity.pokemobs.helper.EntityAiPokemob.func_70626_be(EntityAiPokemob.java:1420)
[18:46:26] [Server thread/INFO] [STDERR/]: [pokecube.core.ai.thread.PokemobAIThread$AIStuff:tick:80]: 	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2146)
[18:46:26] [Server thread/INFO] [STDERR/]: [pokecube.core.ai.thread.PokemobAIThread$AIStuff:tick:80]: 	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:570)
[18:46:26] [Server thread/INFO] [STDERR/]: [pokecube.core.ai.thread.PokemobAIThread$AIStuff:tick:80]: 	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:155)
[18:46:26] [Server thread/INFO] [STDERR/]: [pokecube.core.ai.thread.PokemobAIThread$AIStuff:tick:80]: 	at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:41)
[18:46:26] [Server thread/INFO] [STDERR/]: [pokecube.core.ai.thread.PokemobAIThread$AIStuff:tick:80]: 	at pokecube.core.entity.pokemobs.helper.EntityTameablePokemob.func_70636_d(EntityTameablePokemob.java:454)
[18:46:26] [Server thread/INFO] [STDERR/]: [pokecube.core.ai.thread.PokemobAIThread$AIStuff:tick:80]: 	at pokecube.core.entity.pokemobs.helper.EntityEvolvablePokemob.func_70636_d(EntityEvolvablePokemob.java:346)
[18:46:26] [Server thread/INFO] [STDERR/]: [pokecube.core.ai.thread.PokemobAIThread$AIStuff:tick:80]: 	at pokecube.core.entity.pokemobs.helper.EntityAiPokemob.func_70636_d(EntityAiPokemob.java:766)
[18:46:26] [Server thread/INFO] [STDERR/]: [pokecube.core.ai.thread.PokemobAIThread$AIStuff:tick:80]: 	at pokecube.core.entity.pokemobs.helper.EntityHungryPokemob.func_70636_d(EntityHungryPokemob.java:307)
[18:46:26] [Server thread/INFO] [STDERR/]: [pokecube.core.ai.thread.PokemobAIThread$AIStuff:tick:80]: 	at pokecube.core.entity.pokemobs.helper.EntityPokemobBase.func_70636_d(EntityPokemobBase.java:551)
[18:46:26] [Server thread/INFO] [STDERR/]: [pokecube.core.ai.thread.PokemobAIThread$AIStuff:tick:80]: 	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1976)
[18:46:26] [Server thread/INFO] [STDERR/]: [pokecube.core.ai.thread.PokemobAIThread$AIStuff:tick:80]: 	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:299)
[18:46:26] [Server thread/INFO] [STDERR/]: [pokecube.core.ai.thread.PokemobAIThread$AIStuff:tick:80]: 	at pokecube.core.entity.pokemobs.helper.EntityTameablePokemob.func_70071_h_(EntityTameablePokemob.java:489)
[18:46:26] [Server thread/INFO] [STDERR/]: [pokecube.core.ai.thread.PokemobAIThread$AIStuff:tick:80]: 	at pokecube.core.entity.pokemobs.helper.EntityStatsPokemob.func_70071_h_(EntityStatsPokemob.java:582)
[18:46:26] [Server thread/INFO] [STDERR/]: [pokecube.core.ai.thread.PokemobAIThread$AIStuff:tick:80]: 	at pokecube.core.entity.pokemobs.helper.EntityMovesPokemob.func_70071_h_(EntityMovesPokemob.java:737)
[18:46:26] [Server thread/INFO] [STDERR/]: [pokecube.core.ai.thread.PokemobAIThread$AIStuff:tick:80]: 	at pokecube.core.entity.pokemobs.helper.EntityEvolvablePokemob.func_70071_h_(EntityEvolvablePokemob.java:376)
[18:46:26] [Server thread/INFO] [STDERR/]: [pokecube.core.ai.thread.PokemobAIThread$AIStuff:tick:80]: 	at pokecube.core.entity.pokemobs.helper.EntityMountablePokemob.func_70071_h_(EntityMountablePokemob.java:557)
[18:46:26] [Server thread/INFO] [STDERR/]: [pokecube.core.ai.thread.PokemobAIThread$AIStuff:tick:80]: 	at pokecube.core.entity.pokemobs.helper.EntityAiPokemob.func_70071_h_(EntityAiPokemob.java:858)
[18:46:26] [Server thread/INFO] [STDERR/]: [pokecube.core.ai.thread.PokemobAIThread$AIStuff:tick:80]: 	at pokecube.core.entity.pokemobs.helper.EntityHungryPokemob.func_70071_h_(EntityHungryPokemob.java:370)
[18:46:26] [Server thread/INFO] [STDERR/]: [pokecube.core.ai.thread.PokemobAIThread$AIStuff:tick:80]: 	at pokecube.core.entity.pokemobs.helper.EntityPokemobBase.func_70071_h_(EntityPokemobBase.java:606)
[18:46:26] [Server thread/INFO] [STDERR/]: [pokecube.core.ai.thread.PokemobAIThread$AIStuff:tick:80]: 	at net.minecraft.world.World.func_72866_a(World.java:1951)
[18:46:26] [Server thread/INFO] [STDERR/]: [pokecube.core.ai.thread.PokemobAIThread$AIStuff:tick:80]: 	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:837)
[18:46:26] [Server thread/INFO] [STDERR/]: [pokecube.core.ai.thread.PokemobAIThread$AIStuff:tick:80]: 	at net.minecraft.world.World.func_72870_g(World.java:1920)
[18:46:26] [Server thread/INFO] [STDERR/]: [pokecube.core.ai.thread.PokemobAIThread$AIStuff:tick:80]: 	at net.minecraft.world.World.func_72939_s(World.java:1743)
[18:46:26] [Server thread/INFO] [STDERR/]: [pokecube.core.ai.thread.PokemobAIThread$AIStuff:tick:80]: 	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:618)
[18:46:26] [Server thread/INFO] [STDERR/]: [pokecube.core.ai.thread.PokemobAIThread$AIStuff:tick:80]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:707)
[18:46:26] [Server thread/INFO] [STDERR/]: [pokecube.core.ai.thread.PokemobAIThread$AIStuff:tick:80]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:385)
[18:46:26] [Server thread/INFO] [STDERR/]: [pokecube.core.ai.thread.PokemobAIThread$AIStuff:tick:80]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:611)
[18:46:26] [Server thread/INFO] [STDERR/]: [pokecube.core.ai.thread.PokemobAIThread$AIStuff:tick:80]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:469)
[18:46:26] [Server thread/INFO] [STDERR/]: [pokecube.core.ai.thread.PokemobAIThread$AIStuff:tick:80]: 	at java.lang.Thread.run(Unknown Source)
[18:46:26] [Server thread/INFO] [STDERR/]: [pokecube.core.ai.thread.PokemobAIThread$AIStuff:tick:80]: java.lang.IllegalArgumentException: Comparison method violates its general contract!

PokeCube Core: 3.3.8
PokeCube Mobs: 2.1.3
PokeCube Revival: 3.3.7
ThutCore: 3.1.5
Forge: 1976

**Comment by XileForce** [comment]
This error has been fixed by a server reboot for now, but figured you still may want to know.

**Comment by Thutmose** [comment]
Should be fixed in ThutCore 3.1.7
