### ISSUE TITLE
[1.9.4] SpongeForge & PC Block Issue

### ISSUE THREAD

**Issue by XileForce** [Thutmose/Pokecube#81]
An issue that only occurs when trying to run pokecubes mod with sponge. Not sure whose side the issue is on, but figured id post it here first. Basically you cannot open the PC and it spams this each time you click it.

[00:22:28] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_92]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_92]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:666) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:385) [lb.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:611) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:469) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_92]
Caused by: java.lang.NullPointerException
	at pokecube.core.CommonProxyPokecube.getPlayer(CommonProxyPokecube.java:73) ~[CommonProxyPokecube.class:?]
	at pokecube.core.blocks.pc.InventoryPC.getPC(InventoryPC.java:122) ~[InventoryPC.class:?]
	at pokecube.core.blocks.pc.BlockPC.func_180639_a(BlockPC.java:123) ~[BlockPC.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:179) ~[lt.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:680) ~[mc.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[jh.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[jh.class:?]
	at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:121) ~[PacketUtil.class:1.9.4-1968-5.0.0-BETA-1503]
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$0(SourceFile:39) ~[fj$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fj$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_92]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_92]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
	... 5 more

PokeCube Core: 3.3.8
PokeCube Mobs: 2.1.3
PokeCube Revival: 3.3.7
ThutCore: 3.1.5
Forge: 1976

**Comment by XileForce** [comment]
seems fixed in newest builds of sponge and pokecubes
