### ISSUE TITLE
Server Crash, Trainer Related.

### ISSUE THREAD

**Issue by doctorkreger** [Thutmose/Pokecube#86]
#### Issue Description:
Server closes with following message:

--- Minecraft Crash Report ----

WARNING: coremods are present:
  AppleCore (AppleCore-mc1.9.4-1.3.4.jar)
  NWRTweak (redstonepaste-mc1.9.4-1.7.4.jar)
  EnderCorePlugin (EnderCore-1.9.4-0.4.0.26-alpha.jar)
Contact their authors BEFORE contacting forge

// Don't be sad. I'll do better next time, I promise!

Time: 6/30/16 4:21 PM
Description: Ticking entity

java.lang.ArrayIndexOutOfBoundsException: 6
	at pokecube.adventures.entity.helper.EntityHasPokemobs.getNextPokemob(EntityHasPokemobs.java:300)
	at pokecube.adventures.ai.trainers.EntityAITrainer.func_75246_d(EntityAITrainer.java:203)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:766)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2146)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:570)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:155)
	at pokecube.adventures.entity.helper.EntityHasPokemobs.func_70636_d(EntityHasPokemobs.java:106)
	at pokecube.adventures.entity.trainers.EntityTrainer.func_70636_d(EntityTrainer.java:343)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1976)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:299)
	at pokecube.adventures.entity.trainers.EntityTrainer.func_70071_h_(EntityTrainer.java:405)
	at net.minecraft.world.World.func_72866_a(World.java:1951)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:837)
	at net.minecraft.world.World.func_72870_g(World.java:1920)
	at net.minecraft.world.World.func_72939_s(World.java:1743)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:618)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:707)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:385)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:611)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:469)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at pokecube.adventures.entity.helper.EntityHasPokemobs.getNextPokemob(EntityHasPokemobs.java:300)
	at pokecube.adventures.ai.trainers.EntityAITrainer.func_75246_d(EntityAITrainer.java:203)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:766)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2146)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:570)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:155)
	at pokecube.adventures.entity.helper.EntityHasPokemobs.func_70636_d(EntityHasPokemobs.java:106)
	at pokecube.adventures.entity.trainers.EntityTrainer.func_70636_d(EntityTrainer.java:343)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1976)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:299)
	at pokecube.adventures.entity.trainers.EntityTrainer.func_70071_h_(EntityTrainer.java:405)
	at net.minecraft.world.World.func_72866_a(World.java:1951)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:837)
	at net.minecraft.world.World.func_72870_g(World.java:1920)

-- Entity being ticked --
Details:
	Entity Type: pokecube_adventures.pokecube:trainer (pokecube.adventures.entity.trainers.EntityTrainer)
	Entity ID: 2
	Entity Name: Beauty Joyce
	Entity's Exact location: 91.42, 61.84, 161.12
	Entity's Block location: World: (91,61,161), Chunk: (at 11,3,1 in 5,10; contains blocks 80,0,160 to 95,255,175), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, -0.03, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1743)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:618)

-- Affected level --
Details:
	Level name: world
	All players: 3 total; [EntityPlayerMP['LadySinger'/1106, l='world', x=243.92, y=74.58, z=153.11], EntityPlayerMP['lordhelmet1'/9211, l='world', x=80.23, y=11.00, z=272.21], EntityPlayerMP['RedDoomYak'/10890, l='world', x=93.09, y=62.07, z=169.08]]
	Chunk stats: ServerChunkCache: 1668 Drop: 0
	Level seed: 1977900120
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (196,82,228), Chunk: (at 4,5,4 in 12,14; contains blocks 192,0,224 to 207,255,239), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 11407600 game time, 1248450 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 43582 (now: false), thunder time: 19678 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:707)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:385)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:611)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:469)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.9.4
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_91, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2319860056 bytes (2212 MB) / 4203216896 bytes (4008 MB) up to 4203216896 bytes (4008 MB)
	JVM Flags: 2 total; -Xmx4096M -Xms4096M
	IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 104
	FML: MCP 9.28 Powered by Forge 12.17.0.1976 60 mods loaded, 60 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.9.4.3.jar) 
	UCHIJAAAA	Forge{12.17.0.1976} [Minecraft Forge] (forge-1.9.4.3.jar) 
	UCHIJAAAA	actuallyadditions{1.9.4-r45} [Actually Additions] (ActuallyAdditions-1.9.4-r45.jar) 
	UCHIJAAAA	alt{1.05} [Additional Loot Tables] (AdditionalLootTables_1.9.4-1.05.jar) 
	UCHIJAAAA	adobeblocks{6.0.0.13} [Adobe Blocks 2] (AdobeBlocks-6.0.0.13.jar) 
	UCHIJAAAA	adobeblocksvc{3.2-fork} [Adobe Blocks Version Checker] (AdobeBlocks-6.0.0.13.jar) 
	UCHIJAAAA	JEI{3.6.7.216} [Just Enough Items] (jei_1.9.4-3.6.7.216.jar) 
	UCHIJAAAA	AppleCore{1.3.4} [AppleCore] (AppleCore-mc1.9.4-1.3.4.jar) 
	UCHIJAAAA	basemetals{2.3.2} [Base Metals] (BaseMetals_1.9.4-2.3.2.6.jar) 
	UCHIJAAAA	Baubles{1.2.1.0} [Baubles] (Baubles-1.9.4-1.2.1.0 (1).jar) 
	UCHIJAAAA	BiomesOPlenty{4.1.0.2033} [Biomes O' Plenty] (BiomesOPlenty-1.9.4-4.1.0.2033-universal.jar) 
	UCHIJAAAA	BloodMagic{1.9.4-2.0.1-40} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.9.4-2.0.1-40.jar) 
	UCHIJAAAA	Botania{r1.8-312} [Botania] (Botania-unofficial.r1.8-312.jar) 
	UCHIJAAAA	Chameleon{1.9-2.1.4} [Chameleon] (Chameleon-1.9-2.1.4.jar) 
	UCHIJAAAA	claycraft{2.0} [Claycraft] (Claycraftmod v2.0 - MC1.9.4 Forge.jar) 
	UCHIJAAAA	nt{1.0} [Climbing Claw] (ClimbingClawV1.0[1.9.4].jar) 
	UCHIJAAAA	cookingforblockheads{3.1.26} [Cooking for Blockheads] (CookingForBlockheads-mc1.9.4-3.1.26.jar) 
	UCHIJAAAA	MineTweaker3{3.0.9} [MineTweaker 3] (CraftTweaker-1.9-3.0.9.jar) 
	UCHIJAAAA	endercore{1.9.4-0.4.0.26-alpha} [EnderCore] (EnderCore-1.9.4-0.4.0.26-alpha.jar) 
	UCHIJAAAA	EnderIO{1.9.4-3.0.0.46_alpha} [Ender IO] (EnderIO-1.9.4-3.0.0.46_alpha.jar) 
	UCHIJAAAA	IronChest{6.0.146.788} [Iron Chest] (ironchest-1.9.4-6.0.146.788.jar) 
	UCHIJAAAA	moreanvils{6.0.1.10} [More Anvils] (MoreAnvils-6.0.1.10.jar) 
	UCHIJAAAA	xreliquary{1.9.4-1.3.2.390} [Reliquary] (Reliquary-1.9.4-1.3.2.390.jar) 
	UCHIJAAAA	fluidity{6.0.0.6} [Fluidity] (Fluidity-6.0.0.6.jar) 
	UCHIJAAAA	forestry{5.0.23.170} [Forestry] (forestry_1.9.4-5.0.23.170.jar) 
	UCHIJAAAA	substratum{1.5.0.1} [Substratum] (Substratum-1.9.4-1.5.0.1.jar) 
	UCHIJAAAA	foundry{2.0.0.0-beta5} [Foundry] (Foundry-1.9.4-2.0.0.0-beta5.jar) 
	UCHIJAAAA	fyrestone{0.6.4.1} [Fyrestone] (fyrestone-0.6.4.1.jar) 
	UCHIJAAAA	hempfarmer{1.9.4-1968-1.51} [HempFarmer] (hempfarmer-1.9.4-1968-1.51.jar) 
	UCHIJAAAA	hopperducts{1.4.7} [Hopper Ducts] (hopperducts-mc1.9.4-1.4.7 (1).jar) 
	UCHIJAAAA	inventorysorter{0.9.1+41} [Simple Inventory sorting] (inventorysorter-1.9.4-0.9.1+41.jar) 
	UCHIJAAAA	mantle{1.9.4-0.10.2.jenkins149} [Mantle] (Mantle-1.9.4-0.10.2.jar) 
	UCHIJAAAA	modernmetals{0.11.0} [Modern Metals] (ModernMetals-0.11.0.jar) 
	UCHIJAAAA	moreanvilsvc{3.2} [More Anvils Version Checker] (MoreAnvils-6.0.1.10.jar) 
	UCHIJAAAA	yurtmod{5.01} [Nomadic Tents] (NomadicTents[1.9.4]-5.01.jar) 
	UCHIJAAAA	orespawn{1.0.3} [Ore Spawn] (OreSpawn_1.9.4-1.0.3.jar) 
	UCHIJAAAA	harvestcraft{1.9.4-pre} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4c.jar) 
	UCHIJAAAA	thutcore{3.1.6} [ThutCore] (thutcore-1.9.4-3.1.6.jar) 
	UCHIJAAAA	NBTEditpqb{1.8.9-1.0} [In-game NBTEdit - Pokecube Edition] (Pokecube Core-3.4.4.jar) 
	UCHIJAAAA	pokecube{3.4.4} [Pokécube Core] (Pokecube Core-3.4.4.jar) 
	UCHIJAAAA	pokecube_ml{0.1.0} [Pokecube Model Loader] (Pokecube Core-3.4.4.jar) 
	UCHIJAAAA	pokecube_mobs{2.1.4} [Pokécube Mobs] (Pokecube Mobs-2.1.4.jar) 
	UCHIJAAAA	pokecube_adventures{3.4.4} [Pokécube Revival] (Pokecube Revival-3.4.4.jar) 
	UCHIJAAAA	pokecube_compat{1.0} [Pokecube Compat] (Pokecube Revival-3.4.4.jar) 
	UCHIJAAAA	redstonepaste{1.7.4} [Redstone Paste] (redstonepaste-mc1.9.4-1.7.4.jar) 
	UCHIJAAAA	Roguelike{1.5.3} [Roguelike Dungeons] (RoguelikeDungeons-1.9.4-1.5.3.jar) 
	UCHIJAAAA	roots{0.007} [Roots] (roots-0.007.jar) 
	UCHIJAAAA	AS_Ruins{16.1} [Ruins Spawning System] (Ruins-1.9.4.jar) 
	UCHIJAAAA	SaltMod{1.8.c} [Salty Mod] (SaltyMod-1.9.4-1.8.c_beta-3.jar) 
	UCHIJAAAA	slabcraftmod{5.0} [Slabcraft] (Slabcraftmod v5.0 - MC1.9.4 Forge.jar) 
	UCHIJAAAA	SpiceOfLife{1.3.3} [The Spice of Life] (SpiceOfLife-mc1.9.4-1.3.3.jar) 
	UCHIJAAAA	staircraftmod{5.0} [Staircraft] (Staircraftmod v5.0 - MC1.9.4 Forge.jar) 
	UCHIJAAAA	storagenetwork{1.12.0} [Storage Network] (StorageNetwork-1.9.4-1.12.0.jar) 
	UCHIJAAAA	tconstruct{1.9.4-2.3.3.jenkins263} [Tinkers' Construct] (TConstruct-1.9.4-2.3.3.jar) 
	UCHIJAAAA	thuttech{3.0.3} [Thut's Tech] (thuttech-3.0.3.jar) 
	UCHIJAAAA	torcharrowsmod{1.9.4-2} [TorchArrowsMod] (torcharrows-1.9.4-2.jar) 
	UCHIJAAAA	Torcherino{3.0s} [Torcherino] (Torcherino-3.0s.jar) 
	UCHIJAAAA	AS_UpdateCheck{1.1.7} [AtomicStryker Update Check Mod] (UpdateCheckerMod-1.9.4.jar) 
	UCHIJAAAA	wallcraftmod{5.0} [Wallcraft] (Wallcraftmod v5.0 - MC1.9.4 Forge.jar) 
	Loaded coremods (and transformers): 
AppleCore (AppleCore-mc1.9.4-1.3.4.jar)
  squeek.applecore.asm.TransformerModuleHandler
NWRTweak (redstonepaste-mc1.9.4-1.7.4.jar)
  net.fybertech.nwr.NWRTransformer
EnderCorePlugin (EnderCore-1.9.4-0.4.0.26-alpha.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)

	EnderIO: No known problems detected.
	Profiler Position: N/A (disabled)
	Player Count: 3 / 20; [EntityPlayerMP['LadySinger'/1106, l='world', x=243.92, y=74.58, z=153.11], EntityPlayerMP['lordhelmet1'/9211, l='world', x=80.23, y=11.00, z=272.21], EntityPlayerMP['RedDoomYak'/10890, l='world', x=93.09, y=62.07, z=169.08]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

#### What happens:
Server crashes during trainer fight.  In each case there has been another trainer within aggro range. Just an additional data point. Rebooting server works, but crashes can happen again.

#### What you expected to happen:
Not a crash!

#### Steps to reproduce:

1. Get fought by trainer under some certain circumstances.

____
#### Affected Versions (Do *not* use "latest"):

- Pokecube Core:3.4.4
- Pokecube Revival (if applicable):3.4.4
- Pokecube Mobs (if applicable):2.1.4
- Minecraft: 1.9.4
- Forge:1.9.4-x.1976

**Comment by Thutmose** [comment]
will have this fixed asap.

**Comment by Thutmose** [comment]
Fix uploaded to curse (might take a little bit to show up). if this still occurs in Pokecube Revival 3.4.6, please re-open this with the new crash report.
