### ISSUE TITLE
Ticking entity 1.10

### ISSUE THREAD

**Issue by captcookie** [Thutmose/Pokecube#87]
I have this same crash the last few days. I can reboot my server and it will be fine for a bit, then it just crashes randomly. Today, I updated to the latest versions of everything. It seems there is a ticking entity.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  TransformerLoader (OpenComputers-MC1.10-1.6.0.2-beta.4.jar)
  CXLibraryCore (cxlibrary-1.10-1.2.1.jar)
  EnderCorePlugin (EnderCore-1.10-0.4.0.31-alpha.jar)
  IC2core (industrialcraft-2-2.6.1-ex110.jar)
Contact their authors BEFORE contacting forge

// I'm sorry, Dave.

Time: 6/30/16 10:01 PM
Description: Ticking entity

java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.util.TimSort.mergeHi(TimSort.java:899)
	at java.util.TimSort.mergeAt(TimSort.java:516)
	at java.util.TimSort.mergeCollapse(TimSort.java:441)
	at java.util.TimSort.sort(TimSort.java:245)
	at java.util.Arrays.sort(Arrays.java:1438)
	at thut.api.maths.Matrix3.doTileCollision(Matrix3.java:688)
	at thut.api.maths.Matrix3.doTileCollision(Matrix3.java:607)
	at pokecube.core.entity.pokemobs.helper.EntityPokemobBase.func_70091_d(EntityPokemobBase.java:457)
	at pokecube.core.entity.pokemobs.helper.EntityAiPokemob.func_70612_e(EntityAiPokemob.java:584)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2223)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:155)
	at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:41)
	at pokecube.core.entity.pokemobs.helper.EntityTameablePokemob.func_70636_d(EntityTameablePokemob.java:454)
	at pokecube.core.entity.pokemobs.helper.EntityEvolvablePokemob.func_70636_d(EntityEvolvablePokemob.java:370)
	at pokecube.core.entity.pokemobs.helper.EntityAiPokemob.func_70636_d(EntityAiPokemob.java:770)
	at pokecube.core.entity.pokemobs.helper.EntityHungryPokemob.func_70636_d(EntityHungryPokemob.java:308)
	at pokecube.core.entity.pokemobs.helper.EntityPokemobBase.func_70636_d(EntityPokemobBase.java:554)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2019)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at pokecube.core.entity.pokemobs.helper.EntityTameablePokemob.func_70071_h_(EntityTameablePokemob.java:489)
	at pokecube.core.entity.pokemobs.helper.EntityStatsPokemob.func_70071_h_(EntityStatsPokemob.java:582)
	at pokecube.core.entity.pokemobs.helper.EntityMovesPokemob.func_70071_h_(EntityMovesPokemob.java:737)
	at pokecube.core.entity.pokemobs.helper.EntityEvolvablePokemob.func_70071_h_(EntityEvolvablePokemob.java:376)
	at pokecube.core.entity.pokemobs.helper.EntityMountablePokemob.func_70071_h_(EntityMountablePokemob.java:557)
	at pokecube.core.entity.pokemobs.helper.EntityAiPokemob.func_70071_h_(EntityAiPokemob.java:862)
	at pokecube.core.entity.pokemobs.helper.EntityHungryPokemob.func_70071_h_(EntityHungryPokemob.java:372)
	at pokecube.core.entity.pokemobs.helper.EntityPokemobBase.func_70071_h_(EntityPokemobBase.java:609)
	at net.minecraft.world.World.func_72866_a(World.java:1955)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:837)
	at net.minecraft.world.World.func_72870_g(World.java:1925)
	at net.minecraft.world.World.func_72939_s(World.java:1748)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:618)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.util.TimSort.mergeHi(TimSort.java:899)
	at java.util.TimSort.mergeAt(TimSort.java:516)
	at java.util.TimSort.mergeCollapse(TimSort.java:441)
	at java.util.TimSort.sort(TimSort.java:245)
	at java.util.Arrays.sort(Arrays.java:1438)
	at thut.api.maths.Matrix3.doTileCollision(Matrix3.java:688)
	at thut.api.maths.Matrix3.doTileCollision(Matrix3.java:607)
	at pokecube.core.entity.pokemobs.helper.EntityPokemobBase.func_70091_d(EntityPokemobBase.java:457)
	at pokecube.core.entity.pokemobs.helper.EntityAiPokemob.func_70612_e(EntityAiPokemob.java:584)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2223)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:155)
	at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:41)
	at pokecube.core.entity.pokemobs.helper.EntityTameablePokemob.func_70636_d(EntityTameablePokemob.java:454)
	at pokecube.core.entity.pokemobs.helper.EntityEvolvablePokemob.func_70636_d(EntityEvolvablePokemob.java:370)
	at pokecube.core.entity.pokemobs.helper.EntityAiPokemob.func_70636_d(EntityAiPokemob.java:770)
	at pokecube.core.entity.pokemobs.helper.EntityHungryPokemob.func_70636_d(EntityHungryPokemob.java:308)
	at pokecube.core.entity.pokemobs.helper.EntityPokemobBase.func_70636_d(EntityPokemobBase.java:554)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2019)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at pokecube.core.entity.pokemobs.helper.EntityTameablePokemob.func_70071_h_(EntityTameablePokemob.java:489)
	at pokecube.core.entity.pokemobs.helper.EntityStatsPokemob.func_70071_h_(EntityStatsPokemob.java:582)
	at pokecube.core.entity.pokemobs.helper.EntityMovesPokemob.func_70071_h_(EntityMovesPokemob.java:737)
	at pokecube.core.entity.pokemobs.helper.EntityEvolvablePokemob.func_70071_h_(EntityEvolvablePokemob.java:376)
	at pokecube.core.entity.pokemobs.helper.EntityMountablePokemob.func_70071_h_(EntityMountablePokemob.java:557)
	at pokecube.core.entity.pokemobs.helper.EntityAiPokemob.func_70071_h_(EntityAiPokemob.java:862)
	at pokecube.core.entity.pokemobs.helper.EntityHungryPokemob.func_70071_h_(EntityHungryPokemob.java:372)
	at pokecube.core.entity.pokemobs.helper.EntityPokemobBase.func_70071_h_(EntityPokemobBase.java:609)
	at net.minecraft.world.World.func_72866_a(World.java:1955)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:837)
	at net.minecraft.world.World.func_72870_g(World.java:1925)

-- Entity being ticked --
Details:
	Entity Type: pokecube_ml.Clefable (pokecube.core.entity.pokemobs.GenericPokemob36)
	Entity ID: 315
	Entity Name: Clefable
	Entity's Exact location: -22.59, 66.00, -590.46
	Entity's Block location: World: (-23,66,-591), Chunk: (at 9,4,1 in -2,-37; contains blocks -32,0,-592 to -17,255,-577), Region: (-1,-2; contains chunks -32,-64 to -1,-33, blocks -512,0,-1024 to -1,255,-513)
	Entity's Momentum: -0.10, -0.30, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1748)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:618)

-- Affected level --
Details:
	Level name: world
	All players: 1 total; [EntityPlayerMP['zackary29'/3862, l='world', x=-29.70, y=66.00, z=-591.13]]
	Chunk stats: ServerChunkCache: 379 Drop: 0
	Level seed: 1323048889321144939
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-57,88,-709), Chunk: (at 7,5,11 in -4,-45; contains blocks -64,0,-720 to -49,255,-705), Region: (-1,-2; contains chunks -32,-64 to -1,-33, blocks -512,0,-1024 to -1,255,-513)
	Level time: 3366025 game time, 262691 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 47396 (now: false), thunder time: 125751 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.10
	Operating System: Linux (amd64) version 3.13.0-87-generic
	Java Version: 1.8.0_91, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 250202488 bytes (238 MB) / 1234214912 bytes (1177 MB) up to 6372720640 bytes (6077 MB)
	JVM Flags: 4 total; -Xmx6144M -Xms128M -XX:MaxMetaspaceSize=256M -XX:+UseConcMarkSweepGC
	IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 104
	FML: MCP 9.32 Powered by Forge 12.18.0.2000 72 mods loaded, 72 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10-12.18.0.2000-1.10.0-universal.jar) 
	UCHIJAAAA	Forge{12.18.0.2000} [Minecraft Forge] (forge-1.10-12.18.0.2000-1.10.0-universal.jar) 
	UCHIJAAAA	OpenComputers|Core{1.6.0.2-beta.4} [OpenComputers (Core)] (minecraft.jar) 
	UCHIJAAAA	actuallyadditions{1.10-r46} [Actually Additions] (ActuallyAdditions-1.10-r46.jar) 
	UCHIJAAAA	agriculturalexpansion{beta 1.1.15} [Agricultural Expansion] (AgriculturalExpansion[1.9.4][1.10]-beta 1.1.15.jar) 
	UCHIJAAAA	autopackager{1.6.3} [AutoPackager] (autopackager-1.6.3.jar) 
	UCHIJAAAA	bagginses{2.4.2d} [Bagginses] (Bagginses-1.10-3.0.0c.jar) 
	UCHIJAAAA	Baubles{1.2.1.0} [Baubles] (Baubles-1.9.4-1.2.1.0.jar) 
	UCHIJAAAA	betterbuilderswands{0.6.5} [Better Builder's Wands] (BetterBuildersWands-0.6.5-1.10r138+8595fc7.jar) 
	UCHIJAAAA	BiomesOPlenty{4.1.0.2033} [Biomes O' Plenty] (BiomesOPlenty-1.9.4-4.1.0.2033-universal.jar) 
	UCHIJAAAA	ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.10-alpha-1.0.0.jar) 
	UCHIJAAAA	JEI{3.7.1.219} [Just Enough Items] (jei_1.10-3.7.1.219.jar) 
	UCHIJAAAA	BloodMagic{1.9.4-2.0.2-48} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.9.4-2.0.2-48.jar) 
	UCHIJAAAA	Botania{r1.8-311} [Botania] (Botania-unofficial.r1.8-311.jar) 
	UCHIJAAAA	Chameleon{1.9.4-2.1.5} [Chameleon] (Chameleon-1.9.4-2.1.5.jar) 
	UCHIJAAAA	mcmultipart{1.2.0_73} [MCMultiPart] (MCMultiPart-experimental-1.2.0_73-universal.jar) 
	UCHIJAAAA	CharsetLib{0.3.0-pre12} [‽] (Charset-0.3.0-pre12.jar) 
	UCHIJAAAA	CharsetAudio{0.3.0-pre12} [♫] (Charset-0.3.0-pre12.jar) 
	UCHIJAAAA	CharsetCarts{0.3.0-pre12} [U] (Charset-0.3.0-pre12.jar) 
	UCHIJAAAA	CharsetDecoration{0.3.0-pre12} [�?] (Charset-0.3.0-pre12.jar) 
	UCHIJAAAA	CharsetDrama{0.3.0-pre12} [!] (Charset-0.3.0-pre12.jar) 
	UCHIJAAAA	CharsetFarming{0.3.0-pre12} [;] (Charset-0.3.0-pre12.jar) 
	UCHIJAAAA	CharsetGates{0.3.0-pre12} [&] (Charset-0.3.0-pre12.jar) 
	UCHIJAAAA	CharsetPipes{0.3.0-pre12} [|] (Charset-0.3.0-pre12.jar) 
	UCHIJAAAA	CharsetStorage{0.3.0-pre12} [#] (Charset-0.3.0-pre12.jar) 
	UCHIJAAAA	CharsetTweaks{0.3.0-pre12} [*] (Charset-0.3.0-pre12.jar) 
	UCHIJAAAA	CharsetWires{0.3.0-pre12} [+] (Charset-0.3.0-pre12.jar) 
	UCHIJAAAA	CharsetWrench{0.3.0-pre12} [/] (Charset-0.3.0-pre12.jar) 
	UCHIJAAAA	chisel{@VERSION@} [Chisel] (Chisel-MC1.9.4-0.0.5.29.jar) 
	UCHIJAAAA	chiselsandbits{11.3} [Chisels & Bits] (chiselsandbits-11.3.jar) 
	UCHIJAAAA	cookingforblockheads{3.1.26} [Cooking for Blockheads] (CookingForBlockheads-mc1.9.4-3.1.26.jar) 
	UCHIJAAAA	cxlibrary{1.2.1} [CXLibrary] (cxlibrary-1.10-1.2.1.jar) 
	UCHIJAAAA	ElecCore{1.5.292} [ElecCore] (ElecCore-1.9.4-1.5.292.jar) 
	UCHIJAAAA	deepresonance{1.2.0beta35} [DeepResonance] (deepresonance-1.9.4-1.2.0beta35.jar) 
	UCHIJAAAA	EnderBags{2.0.1} [EnderBags] (EnderBags-1.9.4-2.0.0.jar) 
	UCHIJAAAA	endercore{1.10-0.4.0.31-alpha} [EnderCore] (EnderCore-1.10-0.4.0.31-alpha.jar) 
	UCHIJAAAA	EnderIO{1.10-3.0.0.51_alpha} [Ender IO] (EnderIO-1.10-3.0.0.51_alpha.jar) 
	UCHIJAAAA	enderthing{0.6.8} [Enderthing] (enderthing-1.9.4-0.6.8.jar) 
	UCHIJAAAA	flatcoloredblocks{mc1.10-v4.1} [Flat Colored Blocks] (flatcoloredblocks-mc1.10-v4.1.jar) 
	UCHIJAAAA	fe{1.2.1} [Food Expansion] (FoodExpansion1.2.3-1.10.jar) 
	UCHIJAAAA	forestry{5.1.7.188} [Forestry] (forestry_1.10-5.1.7.188.jar) 
	UCHIJAAAA	gravestone{1.4.2} [Gravestone] (Gravestone Mod 1.4.2.jar) 
	UCHIJAAAA	IC2{2.6.1-ex110} [IndustrialCraft 2] (industrialcraft-2-2.6.1-ex110.jar) 
	UCHIJAAAA	InventoryPets{1.4.7.1} [Inventory Pets] (inventorypets-1.10-1.4.7.1.jar) 
	UCHIJAAAA	IronChest{7.0.2.790} [Iron Chest] (ironchest-1.10-7.0.2.790.jar) 
	UCHIJAAAA	mantle{1.10-0.10.3.jenkins156} [Mantle] (Mantle-1.10-0.10.3.jar) 
	UCHIJAAAA	testdummy{1.11} [MmmMmmMmmMmm] (MmmMmmMmmMmm-1.11.jar) 
	UCHIJAAAA	MoreFurnaces{1.8.1} [More Furnaces] (MoreFurnaces-1.10-1.8.1.jar) 
	UCHIJAAAA	Morpheus{1.10-3.1.6} [Morpheus] (Morpheus-1.10-3.1.6.jar) 
	UCHIJAAAA	nethermetals{1.1.2} [Nether Metals] (NetherMetals_1.9-1.1.2.jar) 
	UCHIJAAAA	netherportalfix{1.0} [Nether Portal Fix] (netherportalfix-mc1.9.4-4.0.1.jar) 
	UCHIJAAAA	OpenComputers{1.6.0.2-beta.4} [OpenComputers] (OpenComputers-MC1.10-1.6.0.2-beta.4.jar) 
	UCHIJAAAA	packingtape{0.5.2} [Packing Tape] (PackingTape-1.9.4-0.5.2.jar) 
	UCHIJAAAA	parachutemod{1.5.0} [Parachute Mod] (parachutemod-ng-1.10-1.5.0-407.jar) 
	UCHIJAAAA	planttech{1.6.0} [Planttech] (planttech-1.6.0 - 1.10.jar) 
	UCHIJAAAA	thutcore{3.1.6} [ThutCore] (thutcore-1.9.4-3.1.6.jar) 
	UCHIJAAAA	NBTEditpqb{1.8.9-1.0} [In-game NBTEdit - Pokecube Edition] (Pokecube Core-4.1.4.jar) 
	UCHIJAAAA	pokecube{4.1.4} [Pok�cube Core] (Pokecube Core-4.1.4.jar) 
	UCHIJAAAA	pokecube_ml{0.1.0} [Pokecube Model Loader] (Pokecube Core-4.1.4.jar) 
	UCHIJAAAA	pokecube_mobs{2.1.4} [Pok�cube Mobs] (Pokecube Mobs-2.1.4.jar) 
	UCHIJAAAA	pokecube_adventures{4.1.4} [Pok�cube Revival] (Pokecube Revival-4.1.4.jar) 
	UCHIJAAAA	pokecube_compat{1.0} [Pokecube Compat] (Pokecube Revival-4.1.4.jar) 
	UCHIJAAAA	RandomUtilities{3.1.1} [Random Utilities] (Random Utilities-1.9.4-3.1.1.jar) 
	UCHIJAAAA	StorageDrawers{1.9.4-3.1.10} [Storage Drawers] (StorageDrawers-1.9.4-3.1.10.jar) 
	UCHIJAAAA	refinedstorage{0.8} [Refined Storage] (refinedstorage-0.8.jar) 
	UCHIJAAAA	xreliquary{1.10-1.3.2.409} [Reliquary] (Reliquary-1.10-1.3.2.409.jar) 
	UCHIJAAAA	rftools{4.67} [RFTools] (rftools-1.10-4.67.jar) 
	UCHIJAAAA	supercraftingframe{1.2.0.79} [Super Crafting Frame] (supercraftingframe-1.10-1.2.0.79.jar) 
	UCHIJAAAA	tconstruct{1.10-2.3.3a.jenkins271} [Tinkers' Construct] (TConstruct-1.10-2.3.3a.jar) 
	UCHIJAAAA	theoneprobe{1.0.12} [The One Probe] (theoneprobe-1.10-1.0.12.jar) 
	UCHIJAAAA	vending{1.3.4} [vending] (vending-1.9.4-1.3.4.jar) 
	Loaded coremods (and transformers): 
TransformerLoader (OpenComputers-MC1.10-1.6.0.2-beta.4.jar)
  li.cil.oc.common.asm.ClassTransformer
CXLibraryCore (cxlibrary-1.10-1.2.1.jar)
  cubex2.cxlibrary.CoreModTransformer
EnderCorePlugin (EnderCore-1.10-0.4.0.31-alpha.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
IC2core (industrialcraft-2-2.6.1-ex110.jar)
  
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)

	EnderIO: No known problems detected.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 21; [EntityPlayerMP['zackary29'/3862, l='world', x=-29.70, y=66.00, z=-591.13]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

____
#### Affected Versions (Do *not* use "latest"):

- Pokecube Core:
- Pokecube Revival (if applicable):
- Pokecube Mobs (if applicable):
- Minecraft: 1.10
- Forge: 2000

**Comment by Thutmose** [comment]
This should be fixed in ThutCore 3.1.7 which has been uploaded to curse.
